package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter13 {


    String[] questionsSet1 = {
            "1. ……… is a branch of information technology known as information security.",
            "(1) Computer security ",
            "(2) Cyber security",
            "(3) IT security",
            "(4) All of these",
            "(5) None of these",
            "2. It takes advantages of basic hardware and software security characteristics.",
            "(1) System design",
            "(2) Data access control",
            "(3) System access control",
            "(4) None of these",
            "(5) All of these",
            "3. Verification of a login name and password is known as <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) configuration ",
            "(2) accessibility",
            "(3) authentication ",
            "(4) logging in",
            "(5) Other than those given as options",
            "4. If you are allowing a person on the network based on the credentials to maintain the security of your network, then this act refers to the process of <font color=#0099ff>(IBPS PO 2016)</font>",
            "(1) Authentication ",
            "(2) Automation",
            "(3) Firewall ",
            "(4) Encryption",
            "(5) None of these",
            "5. The scrambling of code is known as",
            "(1) Encryption ",
            "(2) Firewalling",
            "(3) Scrambling ",
            "(4) Deception",
            "(5) Permuting",
            "6. The main reason to encrypt a file is to",
            "(1) reduce its size",
            "(2) secure it for transmission",
            "(3) prepare it for backup",
            "(4) include it in the start-up sequence",
            "(5) None of these",
            "7. Cracked softwares are another source of",
            "(1) E-mail attack ",
            "(2) Virus attack",
            "(3) Trojan horse ",
            "(4) All of these",
            "(5) None of these",
            "8. A malware is an",
            "(1) program ",
            "(2) hardware",
            "(3) a person ",
            "(4) None of these",
            "(5) All of these",
            "9. Softwares such as Viruses, Worms and Trojan Horses that have a malicious content, is known as <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Malicious software (malware)",
            "(2) adware ",
            "(3) scareware",
            "(4) spyware ",
            "(5) firewall",
            "10. Viruses, trojan horses and worms are <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) able to harm computer system",
            "(2) unable to detect if present on computer",
            "(3) user-friendly applications",
            "(4) harmless applications resident on computer",
            "(5) None of the above",
            "11. It is a self-replicating program that infects computer and spreads by inserting copies of itself into other executable code or documents.",
            "(1) Keylogger ",
            "(2) Worm",
            "(3) Virus ",
            "(4) Cracker",
            "(5) None of these",
            "12. A computer virus is",
            "(1) deliberately created",
            "(2) created accidently",
            "(3) produced as result of some program error",
            "(4) All of the above",
            "(5) None of these",
            "13. …… are often delivered to a PC through an mail attachment and are often designed to do harm. <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) Portals",
            "(2) Spam",
            "(3) Viruses",
            "(4) Other than those given as options",
            "(5) E-mail messages",
            "14. Which of the following refers to dangerous programs that can be ‘caught’ of opening E-mail attachments and downloading software from the Internet? <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) Utility ",
            "(2) Virus",
            "(3) Honey Pot ",
            "(4) Spam",
            "(5) App",
            "15. A program designed to destroy data on your computer which can travel to ‘infect’ other computers is called a <font color=#0099ff>(RBI Grade B 2012)</font>)</font>",
            "(1) disease ",
            "(2) torpedo ",
            "(3) hurricane ",
            "(4) virus",
            "(5) infector",
            "16. If your computer rebooting itself then it is likely that <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) it has a virus",
            "(2) it does not have enough memory",
            "(3) there is no printer",
            "(4) there has been a power surge",
            "(5) it needs a CD-ROM",
            "17. Computer virus is <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) a hardware",
            "(2) windows tool",
            "(3) a computer program",
            "(4) a system software",
            "(5) None of the above",
            "18. Which among the following is related to the internet and mail?",
            "(1) Boot-UP ",
            "(2) Magnetic Tapes",
            "(3) Applications Software",
            "(4) Paging",
            "(5) Virus",
            "19. The first PC virus was developed in",
            "(1) 1980 ",
            "(2) 1984 ",
            "(3) 1986 ",
            "(4) 1988",
            "(5) None of these",
            "20. The first computer virus is",
            "(1) creeper ",
            "(2) PARAM",
            "(3) the famous ",
            "(4) HARLIE",
            "(5) None of these",
    };
    String[] answersSet1 = {
            "(4)","(1)","(3)","(1)","(1)","(2)","(2)","(1)","(1)","(1)","(3)","(1)","(3)","(2)","(4)","(1)","(3)","(5)","(3)","(1)"

    };
    String[] questionsSet2 = {
            "1. Which virus spreads in application software?",
            "(1) Macro virus ",
            "(2) Boot virus",
            "(3) File virus ",
            "(4) Antivirus",
            "(5) None of these",
            "2. The ......... of a threat measures its potential impact on a system. <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) vulnerabilities ",
            "(2) counter measures",
            "(3) degree of harm ",
            "(4) susceptibility",
            "(5) None of these",
            "3. Which of the following is the type of software that has self-replicating software that causes damage to files and system?",
            "(1) Viruses ",
            "(2) Trojan horses",
            "(3) Bots ",
            "(4) Worms",
            "(5) None of these",
            "4. Like a virus, it is also a self-replicating program. The difference between a virus and it is that a worm does not create copies of itself on one system it propagates through computer networks.",
            "(1) Keylogger ",
            "(2) Worm",
            "(3) Cracker ",
            "(4) None of these",
            "(5) None of these",
            "5. A worm",
            "(1) can automatically move in network",
            "(2) can only be transferred with human intervention",
            "(3) worms are harmless",
            "(4) None of the above",
            "(5) None of these",
            "6. Worm is a program that infects computer and spreads by inserting copies of itself into other executable code or documents.",
            "(1) Self attach ",
            "(2) Self-replicating",
            "(3) Non-self-replicating ",
            "(4) Hacking",
            "(5) None of these",
            "7. A computer virus normally attaches itself to another computer program known as a <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) host program ",
            "(2) target program",
            "(3) backdoor program ",
            "(4) bluetooth",
            "(5) trojan horse",
            "8. These are program designed as to seem to being or be doing one thing, but actually being or doing another.",
            "(1) Trojan horses ",
            "(2) Keylogger",
            "(3) Worm ",
            "(4) Cracker",
            "(5) None of these",
            "9. Viruses that fool a user into downloading and/or executing them by pretending to be useful applications are also sometimes called",
            "(1) Trojan horses ",
            "(2) Keylogger",
            "(3) Worm ",
            "(4) Cracker",
            "(5) None of these",
            "10. A ......... is a small program embedded inside of a GIF image.",
            "(1) Web bug ",
            "(2) cookie",
            "(3) spyware application ",
            "(4) spam",
            "(5) None of these",
            "11. Hackers often gain entry to a network be pretending to be at a legitimate computer",
            "(1) spoofing ",
            "(2) forging",
            "(3) IP spoofing ",
            "(4) All of these",
            "(5) None of these",
            "12. It is a situation in which one person or program successfully masquerades as another by falsifying data and thereby gaining illegitimate access.",
            "(1) Sspoofing attack ",
            "(2) Vulnerability scanner",
            "(3) Packet sniffer ",
            "(4) Rootkit",
            "(5) None of these",
            "13. Attempt to gain unauthorised access to a user’s system or information by pretending to be the user? <font color=#0099ff>(IBPS RRB PO 2018)</font>",
            "(1) Spoofing ",
            "(2) Hacker",
            "(3) Cracker ",
            "(4) Phishing",
            "(5) None of these",
            "14. Which of the following enables to determine how often a user visited a Website? <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Hacker ",
            "(2) Spammer",
            "(3) Phish ",
            "(4) Identify theft",
            "(5) Cookie",
            "15. A person who uses his or her expertise to gain access to other people computers to get information illegally or do damage is a <font color=#0099ff>(Allahabad Bank PO 2011)</font> Or A person who uses his expertise for software? <font color=#0099ff>(IBPS RRB PO 2018)</font>",
            "(1) spammer ",
            "(2) hacker",
            "(3) instant messenger ",
            "(4) All of these",
            "(5) None of these",
            "16. Hackers",
            "(1) all have the same motive",
            "(2) are another name of users",
            "(3) many legally break into computer as long as they do not do any damage",
            "(4) are people who are allergic to computers",
            "(5) break into other people’s computer",
            "17. What is a person called who uses a computer to cause harm to people or destroy critical systems? <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Cyber Terrorist",
            "(2) Black-hat-Hacker",
            "(3) Cyber Cracker",
            "(4) Hacktivist",
            "(5) Other than those given as options",
            "18. An act of sending e-mails or creating webpages that are designed to collect and individual’s online bank, credit card or other login information?",
            "(1) Phishing ",
            "(2) Spam",
            "(3) Hacking ",
            "(4) Cracking",
            "(5) None of these",
            "19. ......... are attempts by individuals to obtain confidential information from you by falsifying their identity. <font color=#0099ff>(IBPS PO 2011, IBPS Clerk 2013)</font>",
            "(1) Phishing trips ",
            "(2) Computer viruses",
            "(3) Spyware scams ",
            "(4) Viruses",
            "(5) Phishing scams",
            "20. Which of the following is a criminal activity attempting to acquire sensitive information such as passwords, credit cards, debits by masquerading as a trustworthy person or business in an electronic communication? <font color=#0099ff>(IBPS Clerk 2010)</font>",
            "(1) Spoofing ",
            "(2) Phishing",
            "(3) Stalking ",
            "(4) Hacking",
            "(5) None of these"
    };
    String[] answersSet2 = {
            "(1)","(3)","(4)","(2)","(1)","(2)","(5)","(1)","(1)","(3)","(3)","(1)","(1)","(1)","(2)","(5)","(3)","(1)","(1)","(2)"

    };
    String[] questionsSet3 = {
            "1. All of the following are examples of real-security and privacy risks except <font color=#0099ff>(SBI PO 2011, IBPS Clerk 2014)</font>",
            "(1) hackers ",
            "(2) spam",
            "(3) viruses ",
            "(4) identify theft",
            "(5) None of these",
            "2. Junk E-mail is also called <font color=#0099ff>(Union Bank of India 2011)</font>",
            "(1) spam ",
            "(2) spoof",
            "(3) sniffer script ",
            "(4) spool",
            "(5) None fo these",
            "3. ……… is a type of electronic spam where unsolicited messages are sent by e-mail.",
            "(1) Trash mail ",
            "(2) Cram mail",
            "(3) Draft mail ",
            "(4) Spam mail",
            "(5) None of these",
            "4. Adware is something",
            "(1) which is added to your computers",
            "(2) by adding this performance of your computer increases",
            "(3) software that gets different advertisement",
            "(4) None of the above",
            "(5) All of these",
            "5. It is a toolkit for hiding the fact that a computer’s security has been compromised, is a general description of a set of programs which work to subvert control of an operating system from its legitimate (in accordance with established rules) operators.",
            "(1) Rootkit ",
            "(2) Keylogger",
            "(3) Worm ",
            "(4) Cracker",
            "(5) None of these",
            "6. It is a prepared application that takes advantage of a known weakness.",
            "(1) Security exploit",
            "(2) Vulnerability scanner",
            "(3) Packet sniffer",
            "(4) Rootkit",
            "(5) None of these",
            "7. It is a tool used to quickly check computers on a network for known weaknesses.",
            "(1) Security exploit ",
            "(2) Vulnerability scanner",
            "(3) Packet sniffer ",
            "(4) Rootkit",
            "(5) None of these",
            "8. A ......... is anything that can cause harm.",
            "(1) vulnerability ",
            "(2) phishing",
            "(3) threat ",
            "(4) spoof",
            "(5) None of these",
            "9. An antivirus is a (n)",
            "(1) program code ",
            "(2) computer",
            "(3) company name ",
            "(4) application software",
            "(5) None of these",
            "10. Antivirus software is an example of",
            "(1) business software",
            "(2) an operating system",
            "(3) a security",
            "(4) an office suite",
            "(5) None of these",
            "11. A digital signature is an <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) scanned signature",
            "(2) signature in binary form",
            "(3) encrypting information",
            "(4) handwritten signature",
            "(5) None of the above",
            "12. To protect yourself from computer hacker intrusions, you should install a <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) firewall ",
            "(2) mailer",
            "(3) macro ",
            "(4) script",
            "(5) None of these",
            "13. Which one of the following is a key function of firewall? <font color=#0099ff>(SBI PO 2010)</font>",
            "(1) Monitoring ",
            "(2) Deleting",
            "(3) Copying ",
            "(4) Moving",
            "(5) None of these",
            "14. Mechanism to protect network from outside attack is",
            "(1) firewall ",
            "(2) antivirus",
            "(3) digital signature ",
            "(4) formatting",
            "(5) None of these",
            "15. A firewall operated by <font color=#0099ff>(SBI Clerk 2010)</font>",
            "(1) the pre-purchase phase",
            "(2) isolating intranet from extranet",
            "(3) screeningpacketsto/fromthenetworkand providecontrollablefilteringofnetworktraffic",
            "(4) All of the above",
            "(5) None of the above",
            "16. Coded entries which are used to gain access to a computer system are called",
            "(1) Entry codes ",
            "(2) Passwords",
            "(3) Securitycommands ",
            "(4) Codewords",
            "(5) None of these",
            "17. Password enables users to",
            "(1) get into the system quickly",
            "(2) make efficient use of time",
            "(3) retain confidentiality of files",
            "(4) simplify file structure",
            "(5) None of these",
            "18. Which of the following is the combination of numbers, alphabets along with username used to get access to user account?",
            "(1) Password ",
            "(2) Username",
            "(3) Titlename ",
            "(4) Host-Id",
            "(5) None of these",
            "19. ……… refers to privileges that allow a user to read, write or execute a file.",
            "(1) Authentication",
            "(2) File access permission",
            "(3) Password",
            "(4) Firewall",
            "(5) None of these",
            "20. The unauthorised real-time interception of a private communication such as a phone call, instant message known as",
            "(1) replay ",
            "(2) eavesdropping",
            "(3) patches ",
            "(4) payloads",
            "(5) None of these"
    };
    String[] answersSet3 = {
            "(2)","(1)","(4)","(3)","(1)","(1)","(2)","(1)","(4)","(3)","(3)","(1)","(1)","(1)","(3)","(2)","(3)","(1)","(2)","(2)"

    };
    String[] questionsSet4 = {
            "1. Vendor created program modifications are called <font color=#0099ff>(Allahabad Bank PO 2011)</font>",
            "(1) patches ",
            "(2) antiviruses",
            "(3) hales ",
            "(4) fixes",
            "(5) overlaps",
            "2. Which of the following a computer’s memory, but unlike a virus, it does not replicate itself ? <font color=#0099ff>(SBI PO 2011)</font>",
            "(1) Trojan horse ",
            "(2) Logic bomb",
            "(3) Cracker ",
            "(4) Firewall",
            "(5) None of these",
            "3. Some viruses have a delayed payload, which is sometimes called a",
            "(1) time ",
            "(2) antivirus",
            "(3) bomb ",
            "(4) All of these",
            "(5) None of these",
            "4. Which was the first PC boot sector virus?",
            "(1) Creeper ",
            "(2) Payload",
            "(3) Bomb ",
            "(4) Brain",
            "(5) None of these",
            "5. It hides the true network addresses and used to intercept all messages entering and leaving the network.",
            "(1) Logic bomb ",
            "(2) Firewall",
            "(3) Patches ",
            "(4) Proxy server",
            "(5) None of these",
            "6. It is a software program designed to record (log) every keystroke on the machine on which it runs.",
            "(1) Keylogger ",
            "(2) Worm",
            "(3) Virus ",
            "(4) Cracker",
            "(5) None of these",
            "7. The legal right to use software based on specific restrictions is granted via a <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) software privacy policy",
            "(2) software license",
            "(3) software password manager",
            "(4) software log",
            "(5) None of the above",
            "8. ……… refers to the unauthorised copying and distribution of software. <font color=#0099ff>(IBPS Clerk 2014)</font> OR Illegal copying and distribution of software is <font color=#0099ff>(IBPS RRB PO 2018)</font>",
            "(1) Hacking",
            "(2) Software piracy",
            "(3) Software literacy",
            "(4) Cracking",
            "(5) Copyright",
            "9. Viruses that fool a user into downloading and/or executing them by pretending to be useful applications are also sometimes called",
            "(1) Trojan horses ",
            "(2) Keylogger",
            "(3) Worm ",
            "(4) Cracker",
            "(5) None of these",
            "10. A ......... is a small program embedded inside of a GIF image.",
            "(1) Web bug ",
            "(2) cookie",
            "(3) spyware application ",
            "(4) spam",
            "(5) None of these",
            "11. Hackers often gain entry to a network be pretending to be at a legitimate computer",
            "(1) spoofing ",
            "(2) forging",
            "(3) IP spoofing ",
            "(4) All of these",
            "(5) None of these",
            "12. It is a situation in which one person or program successfully masquerades as another by falsifying data and thereby gaining illegitimate access.",
            "(1) Sspoofing attack ",
            "(2) Vulnerability scanner",
            "(3) Packet sniffer ",
            "(4) Rootkit",
            "(5) None of these",
            "13. Attempt to gain unauthorised access to a user’s system or information by pretending to be the user? <font color=#0099ff>(IBPS RRB PO 2018)</font>",
            "(1) Spoofing ",
            "(2) Hacker",
            "(3) Cracker ",
            "(4) Phishing",
            "(5) None of these",
            "14. Which of the following enables to determine how often a user visited a Website? <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Hacker ",
            "(2) Spammer",
            "(3) Phish ",
            "(4) Identify theft",
            "(5) Cookie",
            "15. A person who uses his or her expertise to gain access to other people computers to get information illegally or do damage is a <font color=#0099ff>(Allahabad Bank PO 2011)</font> Or A person who uses his expertise for software? <font color=#0099ff>(IBPS RRB PO 2018)</font>",
            "(1) spammer ",
            "(2) hacker",
            "(3) instant messenger ",
            "(4) All of these",
            "(5) None of these",
            "16. Hackers",
            "(1) all have the same motive",
            "(2) are another name of users",
            "(3) many legally break into computer as long as they do not do any damage",
            "(4) are people who are allergic to computers",
            "(5) break into other people’s computer",
            "17. What is a person called who uses a computer to cause harm to people or destroy critical systems? <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Cyber Terrorist",
            "(2) Black-hat-Hacker",
            "(3) Cyber Cracker",
            "(4) Hacktivist",
            "(5) Other than those given as options",
            "18. An act of sending e-mails or creating webpages that are designed to collect and individual’s online bank, credit card or other login information?",
            "(1) Phishing ",
            "(2) Spam",
            "(3) Hacking ",
            "(4) Cracking",
            "(5) None of these",
            "19. ......... are attempts by individuals to obtain confidential information from you by falsifying their identity. <font color=#0099ff>(IBPS PO 2011, IBPS Clerk 2013)</font>",
            "(1) Phishing trips ",
            "(2) Computer viruses",
            "(3) Spyware scams ",
            "(4) Viruses",
            "(5) Phishing scams",
            "20. Which of the following is a criminal activity attempting to acquire sensitive information such as passwords, credit cards, debits by masquerading as a trustworthy person or business in an electronic communication? <font color=#0099ff>(IBPS Clerk 2010)</font>",
            "(1) Spoofing ",
            "(2) Phishing",
            "(3) Stalking ",
            "(4) Hacking",
            "(5) None of these"
    };
    String[] answersSet4 = {
            "(1)","(2)","(3)","(4)","(4)","(1)","(2)","(2)","(1)","(3)","(3)","(1)","(1)","(1)","(2)","(5)","(3)","(1)","(1)","(2)"

    };

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }

    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }
}



