package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter8 {


    String[] questionsSet1 = {
            "1. In Windows NT, NT stands for",
            "(1) New Terminology",
            "(2) New Technique",
            "(3) New Technology",
            "(4) Normal Technique",
            "(5) None of these",
            "2. If you are performing Windows 98 operating system to Windows XP you are performing a(n) <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) push up ",
            "(2) China",
            "(3) patch ",
            "(4) pull down",
            "(5) update",
            "3. Which of the following is not a feature of Windows 98?",
            "(1) It supports Internet Explorer 4.0.1.",
            "(2) It also supports many peripheral devices USB, DVD",
            "(3) It was the first operating system to use the WDM",
            "(4) It provides multiple firewall.",
            "(5) None of these",
            "4. In Windows ME, what does ME stand for?",
            "(1) Millennium Edition",
            "(2) Micro Expert",
            "(3) Macro Expert",
            "(4) Multi Expert",
            "(5) None of these",
            "5. Windows XP released in",
            "(1) 2000 ",
            "(2) 1998",
            "(3) 1999 ",
            "(4) 2001",
            "(5) None of these",
            "6. Which of the following is an example of a system software?",
            "(1) Windows 7 ",
            "(2) MS Word 2010",
            "(3) MS PowerPoint 2010 ",
            "(4) Openoffice Writer",
            "(5) None of these",
            "7. Windows 95, Windows 98 and Windows NT are known as what?",
            "(1) Processor ",
            "(2) Domain names",
            "(3) Modems ",
            "(4) Operating systems",
            "(5) None of these",
            "8. Which of the following is not a version of the Windows operating system software for the PC? <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) ME ",
            "(2) 98 ",
            "(3) XP ",
            "(4) Linux",
            "(5) 95",
            "9. Which of the following is not an in-built software application found in MS Windows?",
            "(1) Paint ",
            "(2) CD Player",
            "(3) Disk Defragmentor ",
            "(4) Volume Control",
            "(5) MS Word",
            "10. What is Windows Explorer?<font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) Personal Computer ",
            "(2) Network",
            "(3) File Manager ",
            "(4) Drive",
            "(5) Web Browser",
            "11. Background of screen is known as",
            "(1) application ",
            "(2) window",
            "(3) desktop ",
            "(4) frame",
            "(5) None of these",
            "12. The background image of desktop is called as",
            "(1) graphics ",
            "(2) deskcover",
            "(3) wallback ",
            "(4) wallpaper",
            "(5) None of these",
            "13. The desktop of a computer refers to",
            "(1) the visible screen",
            "(2) the area around the monitor",
            "(3) the top of the mouse pad",
            "(4) the inside of a folder",
            "(5) None of these",
            "14. A blinking indicator that shows you where your next action will happen, is",
            "(1) CPU ",
            "(2) cursor",
            "(3) toolbar ",
            "(4) boot",
            "(5) None of these",
            "15. Graphical pictures that represent an object like file, folder, etc. are <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) task bar ",
            "(2) windows",
            "(3) desktop ",
            "(4) icons",
            "(5) None of these",
            "16. A/An ......... contains programs that can be selected.",
            "(1) pointer ",
            "(2) menu ",
            "(3) icon ",
            "(4) button",
            "(5) None of these",
            "17. To open disk, mouse pointer is placed on disk icon and then",
            "(1) mouse is dragged pushing the button",
            "(2) mouse is double-clicked",
            "(3) mouse is rotated around",
            "(4) mouse is clicked after rotating it",
            "(5) None of these",
            "18. When you want to move an icon on your desktop, this is called",
            "(1) double clicking ",
            "(2) highlighting",
            "(3) dragging ",
            "(4) pointing",
            "(5) None of these",
            "19. To display the contents of a folder in Windows Explorer,you should……. <font color=#0099ff>(SBI PO 2013)</font>",
            "(1) click on it ",
            "(2) collapse it",
            "(3) name it ",
            "(4) give it a password",
            "(5) rename it",
            "20. Factor making Windows popular is",
            "(1) multitasking capacity",
            "(2) desktop features",
            "(3) user friendly",
            "(4) being inexpensive",
            "(5) None of these"
    };
    String[] answersSet1 = {
            "(3)","(5)","(4)","(1)","(4)","(1)","(4)","(4)","(5)","(3)","(3)","(4)","(1)","(2)","(4)","(3)","(2)","(3)","(1)","(2)"

    };
    String[] questionsSet2 = {
            "1. All the deleted files go to",
            "(1) Recycle Bin ",
            "(2) Task Bar",
            "(3) Tool Bar ",
            "(4) Computer",
            "(5) None of these",
            "2. Generally, you access the recycle bin through an icon located",
            "(1) on the desktop ",
            "(2) on the hard drive",
            "(3) on the shortcut menu",
            "(4) in the properties dialog box",
            "(5) None of these",
            "3. Which of the following is used to access a file from the computer store? <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) Insert ",
            "(2) Retrieve",
            "(3) File ",
            "(4) Print",
            "(5) Find",
            "4. The taskbar is located",
            "(1) on the start menu",
            "(2) at the bottom of the screen",
            "(3) on the quick launch toolbar",
            "(4) at the top of the screen",
            "(5) None of these",
            "5. In the split window mode, one title bar looks darker than the other, because <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) darker title bar shows window not in use",
            "(2) darker title bar shows active window",
            "(3) darker title bar shows unavailable window",
            "(4) Both ‘1’ and ‘2’",
            "(5) None of the above",
            "6. Choices are referred to as",
            "(1) options ",
            "(2) exit ",
            "(3) boot ",
            "(4) folder",
            "(5) None of these",
            "7. Date and time are available on the desktop at",
            "(1) Keyboard ",
            "(2) Recycle Bin",
            "(3) My Computer ",
            "(4) Task Bar",
            "(5) None of these",
            "8. Which of the following is appropriate method to shutdown computer?",
            "(1) Click ‘Start’ then select ‘Shut down’",
            "(2) Click ‘Start’ then select ‘Restart’",
            "(3) Click ‘Start’ then switch user",
            "(4) Switch off monitor",
            "(5) None of these",
            "9. End menu is available at which button?",
            "(1) End ",
            "(2) Start ",
            "(3) Turn off ",
            "(4) Restart",
            "(5) Reboot",
            "10. When you install a new program on your computer, it is typically added to the menu.",
            "(1) All Programs ",
            "(2) Select Programs",
            "(3) Start Programs ",
            "(4) Desktop Programs",
            "(5) None of these",
            "11. Why do you log-off from your computer when going out from your office? <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) Someone might steal your files, passwords, etc.",
            "(2) In order to save electricity",
            "(3) Logging off is essential to increase performance",
            "(4) Logging off is mandatory before you go out",
            "(5) Logging off is a good exercise to perform regularly",
            "12. Which of the following refers to the rectangular area for displaying information and running programs? <font color=#0099ff>(SBI PO 2013)</font>",
            "(1) Desktop ",
            "(2) Dialog box",
            "(3) Menu ",
            "(4) Window",
            "(5) Icon",
            "13. Title bar, ribbon, status bar, views and document workspace are components of ......... program.",
            "(1) windows ",
            "(2) browser",
            "(3) explorer ",
            "(4) Website",
            "(5) None of these",
            "14. Active window means the",
            "(1) active window is designated by a different color toolbar that other open window",
            "(2) window that is currently open",
            "(3) Both ‘1’ and ‘2’",
            "(4) window that is last used",
            "(5) None of the above",
            "15. To ‘maximize’ a window means to",
            "(1) fill it to capacity",
            "(2) expand it to fit the desktop",
            "(3) put only like files inside",
            "(4) drag it to the recycle bin",
            "(5) None of these",
            "16. To shrink a window to an icon,",
            "(1) open a group window",
            "(2) minimize a window",
            "(3) maximize a window",
            "(4) restore a window",
            "(5) None of these",
            "17. Which of the following are lists of commands that appear on the screen? <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) GUIs ",
            "(2) Icons",
            "(3) Menus ",
            "(4) Windows",
            "(5) Stack",
            "18. Commands at the top of a screen such; FILE-EDIT-FONT-TOOLS to operate and change things within program comes under",
            "(1) menu bar ",
            "(2) tool bar",
            "(3) user friendly ",
            "(4) Word processor",
            "(5) None of these",
            "19. What is an on-screen display listing of available options of functions on a computer? <font color=#0099ff>(SBI Clerk 2015)</font>",
            "(1) Document ",
            "(2) View",
            "(3) Tool ",
            "(4) Format",
            "(5) Menu",
            "20. Menus are the part of <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) hardware ",
            "(2) user interface",
            "(3) status bar ",
            "(4) monitor",
            "(5) None of these"
    };
    String[] answersSet2 = {
            "(3)","(5)","(4)","(1)","(4)","(1)","(4)","(4)","(5)","(3)","(3)","(4)","(1)","(2)","(4)","(3)","(2)","(3)","(1)","(2)"

    };
    String[] questionsSet3 = {
            "1. For creating a new document, you use which command at File menu?",
            "(1) Open ",
            "(2) Close ",
            "(3) New ",
            "(4) Save",
            "(5) None of these",
            "2. What menu is selected to cut, copy and paste?",
            "(1) File ",
            "(2) Tools",
            "(3) Special ",
            "(4) Edit",
            "(5) None of these",
            "3. Help menu is available at which button?",
            "(1) End ",
            "(2) Start",
            "(3) Turn off ",
            "(4) Restart",
            "(5) None of these",
            "4. It is easier to change the name of file using ......... process.",
            "(1) transforming",
            "(2) christening",
            "(3) renaming",
            "(4) retagging",
            "(5) None of these",
            "5. The steps involved to open a document are <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) select the document to open from the File down menu",
            "(2) click on the Open option in the Tools menu",
            "(3) Both ‘1’ and ‘2’",
            "(4) can be different for different Word document",
            "(5) None of the above",
            "6. A computer message is ‘‘Do you really want to delete the selected file (s)’’? The user clicks ‘Yes’ key. It is called",
            "(1) program response ",
            "(2) user output",
            "(3) user response ",
            "(4) program output",
            "(5) None of these",
            "7. A symbol or question on the screen that prompts you to take action and tell the computer what to do next, is",
            "(1) scanner ",
            "(2) questionnaire",
            "(3) information seeker ",
            "(4) prompt and dialog box",
            "(5) None of these",
            "8. ......... menu type is also known as a drop down menu.",
            "(1) Fly-down ",
            "(2) Pop-down",
            "(3) Pop-up ",
            "(4) Pull-up",
            "(5) Pull-down",
            "9. A .... is an additional set of commands that the computer displays after you make a selection.",
            "(1) dialog box ",
            "(2) sub menu",
            "(3) menu selecting ",
            "(4) All of these",
            "(5) None of these",
            "10. Anything written on the screen is called",
            "(1) cursor ",
            "(2) text",
            "(3) folder ",
            "(4) boot",
            "(5) None of these",
            "11. …… lets you leave a screen or program.",
            "(1) Boot ",
            "(2) Programs",
            "(3) Exit ",
            "(4) Text",
            "(5) None of these",
            "12. A ......... is an icon on the desktop that provides a user with immediate access to a program or file.",
            "(1) kernel ",
            "(2) buffer",
            "(3) shortcut ",
            "(4) spooler",
            "(5) None of these",
            "13. What is the full form of RTF? <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) Richer Text-Formatting",
            "(2) Rich Text Format",
            "(3) Right Text Fishing",
            "(4) Right Text Font",
            "(5) Rich Text Font",
            "14. The extension of paint file is/are",
            "(1) .png ",
            "(2) .jpg",
            "(3) .bmp ",
            "(4) All of these",
            "(5) None of these",
            "15. Which of the following options is used to open calculator?",
            "(1) Start button ® All Programs ® Accessories ® Calculator",
            "(2) Start button ® All Programs ® Calculator",
            "(3) Start button ® Accessories ® Calculator",
            "(4) All of the above",
            "(5) None of these",
            "16. ........ is an easy-to-use interface to play digital media files.",
            "(1) Wordpad ",
            "(2) Notepad",
            "(3) Mediaplayer ",
            "(4) Games",
            "(5) None of these",
            "17. To start Spider Solitaire game, we used to follow",
            "(1) Start ® All Programs ® Games",
            "(2) Start ® All Programs ® Games ® Spider Solitaire",
            "(3) Start ® All programs ® Accessories ® Games ® Spider Solitaire",
            "(4) None of the above",
            "(5) None of these",
            "18. When you cut or copy information it gets place in the …… . <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) clipart ",
            "(2) clipboard",
            "(3) motherboard ",
            "(4) Both ‘1’ and ‘2’",
            "(5) None of these",
            "19. A clipboard <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) is used to save data on disk in the event of a power failure",
            "(2) is able to retain the contents even when computer is switched OFF",
            "(3) is available only in Microsoft Word",
            "(4) is a temporary storage in computer memory and temporarily stores the cut or copied data",
            "(5) None of the above",
            "20. What is the command used to remove text or graphics from a document, the information is then stored on a clipboard so you can paste it.",
            "(1) Chop ",
            "(2) Cut ",
            "(3) Clip ",
            "(4) Cart away",
            "(5) None of these"
    };
    String[] answersSet3 = {
            "(3)","(4)","(2)","(3)","(3)","(3)","(4)","(5)","(1)","(2)","(3)","(3)","(2)","(4)","(1)","(3)","(2)","(2)","(4)","(2)"

    };
    String[] questionsSet4 = {
            "1. A saved document is referred to as a",
            "(1) file ",
            "(2) word ",
            "(3) folder ",
            "(4) project",
            "(5) None of these",
            "2. The name given to a document by the user is called",
            "(1) filename ",
            "(2) program",
            "(3) data ",
            "(4) record",
            "(5) None of these",
            "3. A ......... is a collection of information saved as a unit.",
            "(1) folder ",
            "(2) file",
            "(3) path ",
            "(4) file extension",
            "(5) None of these",
            "4. Information kept about a file includes",
            "(1) print setting ",
            "(2) deletion data",
            "(3) Both ‘1’ and ‘2’ ",
            "(4) size",
            "(5) None of these",
            "5. A file is often referred to as a <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) wizard ",
            "(2) document",
            "(3) pane ",
            "(4) device",
            "(5) documentation",
            "6. Which of the following statements is a false conceiving file names? <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Every file in the same folder must have a unique name",
            "(2) The file name comes before the dot (.)",
            "(3) File extension is another name for the type",
            "(4) The file extension comes before the dot (.) followed by the file name",
            "(5) Files may share the same name or the same extension, but not both at the same time",
            "7. File extensions are used in order to",
            "(1) name the file",
            "(2) ensure the file name is not lost",
            "(3) identify the file",
            "(4) identify the file type",
            "(5) None of these",
            "8. Which of the following contained at the end of the file name and help to determine the type of file? <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) File property ",
            "(2) File type",
            "(3) File name ",
            "(4) File subname",
            "(5) File extension",
            "9. What are .bas, .doc, .htm examples of in computing? <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) Extensions ",
            "(2) Protocols",
            "(3) Database ",
            "(4) Domains",
            "(5) None of these",
            "10. What is the default file extension for all Word documents? <font color=#0099ff>(RBI Asstt. 2012)</font>",
            "(1) WRD ",
            "(2) TXT ",
            "(3) DOC ",
            "4) FIL",
            "(5) WD",
            "11. You organise files by storing them in <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) archives ",
            "(2) lists",
            "(3) indexes ",
            "(4) folders",
            "(5) None of these",
            "12. ......... may be included in other folder while making hierarchical structure folder.",
            "(1) Minifolder",
            "(2) Small folder",
            "(3) Sub-folder",
            "(4) Object folder",
            "(5) None of these",
            "13. Which of the following refers to containers used to store related documents located on the computer? <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) Labels ",
            "(2) Indexes",
            "(3) Programs ",
            "(4) Folders",
            "(5) Sections",
            "14. You can keep your personal files/folders in",
            "(1) My Folder ",
            "(2) Documents",
            "(3) My Files ",
            "(4) My Text",
            "(5) None of these",
            "15. When embedding object into document, one of the following occurs <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) embedded object becomes a part of the document",
            "(2) embedded object remains outside object to the document, but loaded with document",
            "(3) Both becomes a zip file",
            "(4) Both ‘1’ and ‘2’",
            "(5) None of the above",
            "16. Which of the following shortcut keys represents the correct sequence for copy, paste and cut commands?",
            "(1) Ctrl + V; Ctrl+C; Ctrl+V",
            "(2) Ctrl + C; Ctrl+V; Ctrl+X",
            "(3) Ctrl + X; Ctrl+C; Ctrl+V",
            "(4) Ctrl + C; Ctrl+X; Ctrl+V",
            "(5) None of these",
            "17. Which of the following keys is used to delete characters to the left of the cursor? <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) Alt + Delete ",
            "(2) Shift",
            "(3) Esc ",
            "(4) Delete",
            "(5) Backspace",
            "18. To restart the computer, following combination of keys is used",
            "(1) Del + Ctrl ",
            "(2) Backspace + Ctrl",
            "(3) Esc + Ctrl ",
            "(4) Insert + Esc",
            "(5) Ctrl + Alt + Del",
            "19. Which of the following shortcut keys is used to close current or active window? <font color=#0099ff>(IBPS RRB PO Mains 2018)</font>",
            "(1) Alt+F4 ",
            "(2) Ctrl+F4 ",
            "(3) Alt+F6 ",
            "(4) Ctrl+F6",
            "(5) Ctrl+Esc",
            "20. What is the command used to remove text or graphics from a document, the information is then stored on a clipboard so you can paste it.",
            "(1) Chop ",
            "(2) Cut ",
            "(3) Clip ",
            "(4) Cart away",
            "(5) None of these"
    };
    String[] answersSet4 = {
            "(1)","(1)","(2)","(4)","(2)","(4)","(4)","(5)","(1)","(3)","(4)","(3)","(4)","(2)","(1)","(2)","(5)","(5)","(1)","(2)"


    };

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }

    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }
}



