package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter3 {

    String[] questionsSet1 = {
            "1. Any component of the computer you can see and touch is <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) software ",
            "(2) peripheral",
            "(3) storage ",
            "(4) CPU",
            "(5) hardware",
            "2. Which of the following is not a hardware? <font color=#0099ff>(SSC FCI 2012)</font>",
            "(1) Processor chip ",
            "(2) Printer",
            "(3) Mouse ",
            "(4) Java",
            "(5) None of the above",
            "3. A (n) …… device is any hardware component that allows you to enter data and instructions into a computer? <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) interaction ",
            "(2) input",
            "(3) communication ",
            "(4) output",
            "(5) terminal",
            "4. Computer gets …… with the help of mouse, joystick or keyboard.",
            "(1) insert ",
            "(2) delete ",
            "(3) input ",
            "(4) output",
            "(5) None of the above",
            "5. Computer keyboard is an example of",
            "(1) memory device ",
            "(2) input device",
            "(3) output device ",
            "(4) Both ‘2’ and ‘3’",
            "(5) None of the above",
            "6. The most common method of entering text and numerical data into a computer system is through the use of a <font color=#0099ff>(SBI PO 2015)</font>",
            "(1) plotter ",
            "(2) scanner",
            "(3) printer ",
            "(4) keyboard",
            "(5) None of these",
            "7. Which key is also known as toggle keys?",
            "(1) Caps lock ",
            "(2) Num lock",
            "(3) ‘1’ and ‘2’ both ",
            "(4) None of these",
            "(5) None of the above",
            "8. You can use the Tab key to <font color=#0099ff>(SBI Clerk 2013)</font>",
            "(1) move a cursor across the screen",
            "(2) indent a paragraph",
            "(3) move the cursor down the screen",
            "(4) Both ‘1’ and ‘2’",
            "(5) None of the above",
            "9. To move to the beginning of a line of text, press the ...... key.",
            "(1) Page up ",
            "(2) Shift",
            "(3) Home ",
            "(4) Enter",
            "(5) None of the above",
            "10. The …… key will launch the Start button.",
            "(1) Esc ",
            "(2) Shift",
            "(3) Window ",
            "(4) Shortcut",
            "(5) None of the above",
            "11. Spacebar is used for",
            "(1) giving space ",
            "(2) deleting space",
            "(3) moving next line ",
            "(4) All of these",
            "(5) None of the above",
            "(5) None of the above",
            "(1) Deleting Data or Modification",
            "(2) Page Scrolling to view a Document",
            "(3) Launching Start Menu",
            "(4) Initiating Search and Help",
            "(5) Controlling RAM or process execution",
            "13. Shift, Ctrl, Alt are examples of which among the following category? <font color=#0099ff>(IBPS RRB PO Mains 2017)</font>",
            "(1) Modifier Keys ",
            "(2) Primary Keys",
            "(3) Function Keys ",
            "(4) Alternate Keys",
            "(5) Candidate Keys",
            "14. Pointing device includes the following except",
            "(1) mouse ",
            "(2) joystick",
            "(3) trackball ",
            "(4) keyboard",
            "(5) None of the above",
            "15. What type of device is a computer mouse? <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) Storage ",
            "(2) Output",
            "(3) Input ",
            "(4) Input/output",
            "(5) Software",
            "16. Which of these is a pointing and draw device? <font color=#0099ff>(IBPS PO 2012, IBPS Clerk 2013)</font>",
            "(1) Mouse ",
            "(2) Scanner",
            "(3) Printer ",
            "(4) CD-ROM",
            "(5) Keyboard",
            "17. First computer mouse was built by <font color=#0099ff>(SSC CGL 2013)</font>",
            "(1) Douglas Engelbart",
            "(2) William English",
            "(3) Oaniel Coogher",
            "(4) Robert Zawacki",
            "(5) None of the above",
            "18. Keyboard and …… are the examples of input device. <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) monitor ",
            "(2) modem ",
            "(3) printer",
            "(4) mouse ",
            "(5) CPU",
            "19. Which is the best position for operating the mouse? <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) Tail away from the user",
            "(2) Tail towards the user",
            "(3) Tail facing the right",
            "(4) Tail facing the left",
            "(5) None of the above",
            "20. Which button is called as middle button used as third mouse button by pressing on it? <font color=#0099ff>(IBPS RRB PO Mains 2017)</font>",
            "(1) right button ",
            "(2) scroll wheel",
            "(3) touch bar ",
            "(4) light bar",
            "(5) left button"
    };
    String[] answersSet1 = {"(5)", "(4)", "(2)", "(3)", "(2)", "(4)", "(3)", "(2)", "(3)", "(3)", "(1)", "(2)", "(1)", "(4)", "(3)", "(1)", "(1)", "(4)", "(2)", "(2)"
    };

    String[] questionsSet2 = {
            "1. Trackball is an example of a/an <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) programming device ",
            "(2) pointing device",
            "(3) output device ",
            "(4) software device",
            "(5) printing device",
            "2. A joystick is primarily used to/for …… . <font color=#0099ff>(IBPS Clerk 2012, SBI PO 2013)</font>",
            "(1) control sound on the screen",
            "(2) computer gaming",
            "(3) enter text",
            "(4) draw pictures",
            "(5) print text",
            "3. A joystick allows movements in which angle?",
            "(1) 30° ",
            "(2) 60°",
            "(3) 90° ",
            "(4) 360°",
            "(5) None of the above",
            "4. A device, which is used for making drawings, graphics and for menu selection.",
            "(1) Keyboard ",
            "(2) Mouse",
            "(3) Touch screen ",
            "(4) Light Pen",
            "(5) None of the above",
            "5. .......... is generally used in applications like ATM, hospitals, airline reservation etc.",
            "(1) Light pen ",
            "(2) Touch screen",
            "(3) Joystick ",
            "(4) Trackball",
            "(5) None of the above",
            "6. The pattern of printed lines on most products are called <font color=#0099ff>(SBI Clerk 2009)</font>",
            "(1) prices ",
            "(2) OCR",
            "(3) scanners ",
            "(4) barcodes",
            "(5) None of these",
            "7. A barcode reader is an example of",
            "(1) processing device ",
            "(2) storage device",
            "(3) input device ",
            "(4) output device",
            "(5) None of the above",
            "8. An optical input device that interprets pencil marks on paper media is ……… <font color=#0099ff>(IBPS RRB PO Mains 2017)</font>",
            "(1) OMR ",
            "(2) punch card reader",
            "(3) optical scanners ",
            "(4) magnetic tapes",
            "(5) stylus",
            "9. The OCR is used for the preparation of <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) electricity bills ",
            "(2) insurance premium",
            "(3) telephone bills ",
            "(4) All of these",
            "(5) None of these",
            "10. The OCR recognises the …… of the characters with the help of light source. <font color=#0099ff>(SBI Clerk 2009)</font>",
            "(1) size ",
            "(2) shape ",
            "(3) colour",
            "(4) used ink ",
            "(5) None of these",
            "11. What does MICR stand for? <font color=#0099ff>(IBPS Clerk 2014, RBI Grade B 2014)</font>",
            "(1) Magnetic Ink Character Register",
            "(2) Magnetic Ink Code Reader",
            "(3) Magnetic Ink Code Register",
            "(4) Magnetic Ink Character Recognition",
            "(5) Magnetic Ink Cases Reader",
            "12. Large amounts of cheques are processed by using",
            "(1) OCR ",
            "(2) MICR",
            "(3) OMR ",
            "(4) All of these",
            "(5) None of the above",
            "13. Which of the following is/are the kind of smart card?",
            "(1) Memory card ",
            "(2) Micro processor card",
            "(3) ‘1’ and ‘2’ both ",
            "(4) None of these",
            "(5) None of the above",
            "14. Which of the following device which recognises physical traits of an individual?",
            "(1) Smart card ",
            "(2) Biometric sensor",
            "(3) Bard code ",
            "(4) MICR",
            "(5) None of the above",
            "15. A device that makes copies and reproduces text and images is called",
            "(1) CPU ",
            "(2) memory",
            "(3) printer ",
            "(4) scanner",
            "(5) None of the above",
            "16. A........ is used to read handwritten or printed text to make a digital image that is stored in memory. <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) printer ",
            "(2) laser beam",
            "(3) scanner ",
            "(4) touchpad",
            "(5) None of these",
            "17. The input device to be used to get a printed diagram into a computer is the <font color=#0099ff>(IBPS Clerk 2013, IBPS Clerk 2015)</font>",
            "(1) printer ",
            "(2) mouse",
            "(3) keyboard ",
            "(4) touchpad",
            "(5) scanner",
            "18. A scanner scans <font color=#0099ff>(SBI PO 2015)</font>",
            "(1) pictures",
            "(2) text",
            "(3) both pictures and text",
            "(4) Neither pictures nor text",
            "(5) None of the above",
            "19. It is a video capturing device <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) webcam ",
            "(2) microphone",
            "(3) monitor ",
            "(4) mouse",
            "(5) scanner",
            "20. What type of device is a digital camera?",
            "(1) Input ",
            "(2) Output",
            "(3) Software ",
            "(4) Storage",
            "(5) None of the above"
    };
    String[] answersSet2 = {"(2)", "(2)", "(4)", "(4)", "(2)", "(4)", "(3)", "(1)", "(4)", "(2)", "(4)", "(2)", "(3)", "(2)", "(4)", "(3)", "(5)", "(3)", "(1)", "(1)"
    };

    String[] questionsSet3 = {
            "1. Which of the following could be digital input devices for computers? <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) Digital camcorder",
            "(2) Microphone",
            "(3) Scanner",
            "(4) All of these",
            "(5) None of these",
            "2. Which of the following groups consists of only input devices? <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) Mouse, Keyboard, Monitor",
            "(2) Mouse, Keyboard, Printer",
            "(3) Mouse, Keyboard, Plotter",
            "(4) Mouse, Keyboard, Scanner",
            "(5) None of the above",
            "3. Results are obtained from computer through its",
            "(1) input unit ",
            "(2) ALU unit",
            "(3) CU unit ",
            "(4) output unit",
            "(5) None of the above",
            "4. After a picture has been taken with a digital camera and processed appropriately, the actual print of the picture is considered as",
            "(1) data ",
            "(2) output",
            "(3) input ",
            "(4) the process",
            "(5) None of the above",
            "5. Using output device one can ……… <font color=#0099ff>(IBPS RRB PO Mains 2017)</font>",
            "(1) View or Print Data ",
            "(2) Modify Data",
            "(3) Store Data ",
            "(4) Replicate Data",
            "(5) Enter Data",
            "6. Which among the following is the smallest unit in an image in a computer screen? <font color=#0099ff>(IBPS RRB PO Mains 2017)</font>",
            "(1) Unit ",
            "(2) Pixel ",
            "(3) Array",
            "(4) Resolution ",
            "(5) Clip",
            "7. What type of device is a computer monitor? <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) Software ",
            "(2) Processing",
            "(3) Storage ",
            "(4) Input",
            "(5) Output",
            "8. Soft copy refers to …… . <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) printed output ",
            "(2) digitizing",
            "(3) music sounds ",
            "(4) screen output",
            "(5) None of these",
            "9. The higher the resolution of a monitor, the <font color=#0099ff>(IBPS PO 2011)</font>",
            "(1) larger the pixels ",
            "(2) less clear the screen is",
            "(3) further apart the pixels",
            "(4) closer together the pixels",
            "(5) None of the above",
            "10. The most familiar output device for the micro computers is",
            "(1) screen ",
            "(2) TV",
            "(3) printer ",
            "(4) monitor",
            "(5) None of the above",
            "11. The CRT is ……… in shape. <font color=#0099ff>(RBI Grade B 2013, SBI PO 2011)</font>",
            "(1) circular ",
            "(2) rectangular",
            "(3) eclipse ",
            "(4) conical",
            "(5) None of these",
            "12. CRT has a <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) hollow tube ",
            "(2) vacuum tube",
            "(3) long tube ",
            "(4) round tube",
            "(5) None of these",
            "13. The rate at which scanning is repeated in a CRT is called <font color=#0099ff>(SBI Clerk 2009)</font>",
            "(1) refresh rate ",
            "(2) resolution",
            "(3) pitch ",
            "(4) bandwidth",
            "(5) None of these",
            "14. …… provides hard copy output on paper. <font color=#0099ff>(SBI Clerk 2015)</font>",
            "(1) Mouse ",
            "(2) Keyboard",
            "(3) LCD monitor ",
            "(4) Scanner",
            "(5) Printer",
            "15. Printer is an example of <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) output device ",
            "(2) input device",
            "(3) processing device ",
            "(4) storage device",
            "(5) None of these",
            "16. What are the units used to count the speed of a printer? <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) CPM ",
            "(2) DPI",
            "(3) PPM ",
            "(4) BIT",
            "(5) None of these",
            "17. …… printer cannot print more than one characters at a time. <font color=#0099ff>(SSC CHSL 2013)</font>",
            "(1) Line ",
            "(2) Daisy wheel",
            "(3) Laser ",
            "(4) Dot matrix",
            "(5) None of the above",
            "18. Speed of line printer is limited by the speed of <font color=#0099ff>(IBPS PO 2012, Clerk 2013)</font>",
            "(1) paper movements ",
            "(2) cartridge used",
            "(3) length of paper ",
            "(4) All of these",
            "(5) None of these",
            "19. An example of peripheral equipment is",
            "(1) printer ",
            "(2) CPU",
            "(3) spreadsheet ",
            "(4) microcomputer",
            "(5) None of these",
            "20. Dot matrix is a type of",
            "(1) tape ",
            "(2) printer",
            "(3) disk ",
            "(4) bus",
            "(5) None of these"
    };
    String[] answersSet3 = {"(4)", "(4)", "(4)", "(2)", "(1)", "(2)", "(5)", "(4)", "(4)", "(4)", "(2)", "(2)", "(1)", "(5)", "(1)", "(2)", "(4)", "(1)", "(1)", "(2)"
    };
    String[] questionsSet4 = {
            "1. Dot matrix printer is",
            "(1) unidirectional ",
            "(2) bi-directional",
            "(3) sequential ",
            "(4) random",
            "(5) None of the above",
            "2. The impact printers are",
            "(1) dot matrix ",
            "(2) drum",
            "(3) inkjet ",
            "(4) Both ‘1’ and ‘2’",
            "(5) None of the above",
            "3. Drum printer is an example of",
            "(1) input ",
            "(2) output",
            "(3) processing ",
            "(4) storage",
            "(5) None of the above",
            "4. The example of non-impact printers are <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) Laser-Dot matrix ",
            "(2) Inkjet-Laser",
            "(3) Inkjet-Dot matrix ",
            "(4) Dot matrix",
            "(5) None of these",
            "5. Line printer speed is specified in terms of<font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) LPM (Lines Per Minute) ",
            "(2) CPM (Characters Per Minute)",
            "(3) DPM",
            "(4) Any of the above",
            "(5) None of the above",
            "6. In laser printers, printing is achieved by deflecting laser beam on to …… surface of a drum. <font color=#0099ff>(SBI PO, IBPS Clerk 2011, 2013)</font>",
            "(1) magnetised",
            "(2) photosensitive",
            "(3) magnetic",
            "(4) Either ‘1’ or ‘2’",
            "(5) None of these",
            "7. Which of the following printers, are you sure, will not to use if your objective is to print on multi carbon forms?",
            "(1) Daisy wheel ",
            "(2) Dot matrix",
            "(3) Laser ",
            "(4) Thermal",
            "(5) None of these",
            "8. Laser printers belong to",
            "(1) line printer ",
            "(2) page printer",
            "(3) band printer ",
            "(4) dot matrix printer",
            "(5) None of these",
            "9. Which of the following produces high quality output?",
            "(1) Impact printer ",
            "(2) Non-impact printer",
            "(3) Plotter ",
            "(4) Both ‘1’ and ‘2’",
            "(5) None of these",
            "10. Resolution of laser printer is specified in terms of",
            "(1) DPI ",
            "(2) LPM",
            "(3) CPM ",
            "(4) PPM",
            "(5) None of these",
            "11. A hard copy would prepared on a <font color=#0099ff>(SBI Clerk 2013)</font>",
            "(1) line printer ",
            "(2) dot matrix printer",
            "(3) plotter ",
            "(4) type writer terminal",
            "(5) All of these",
            "12. All of the following are examples of input device except",
            "(1) scanner ",
            "(2) mouse",
            "(3) keyboard ",
            "(4) printer",
            "(5) None of these",
            "13. It is used to produce large drawings or images such as construction plans, blueprints for mechnanical object etc.",
            "(1) Printer ",
            "(2) Plotter",
            "(3) MICR ",
            "(4) OCR",
            "(5) None of these",
            "14. What type of devices are computer speakers or headphones? <font color=#0099ff>(IBPS Clerk 2015, SBI Clerk 2012)</font>",
            "(1) Input ",
            "(2) Input/Output ",
            "(3) Software",
            "(4) Storage ",
            "(5) Output",
            "15. Which of the following devices is used to give input as well as to display output?",
            "(1) Tourch screen ",
            "(2) Headsets",
            "(3) Facsimile ",
            "(4) Audio cards",
            "(5) All of these",
            "16. The transfer of data from a CPU to peripheral devices of computer is achieved through <font color=#0099ff>(SSC CGL 2012)</font>",
            "(1) interfaces ",
            "(2) buffer memory",
            "(3) modems ",
            "(4) I/O ports",
            "(5) None of these",
            "17. A parallel port is most often used by a <font color=#0099ff>(SSC CPO 2011)</font>",
            "(1) printer ",
            "(2) monitor",
            "(3) mouse ",
            "(4) external storage device",
            "(5) None of these",
            "18. …… ports provide slow speed data transmission.",
            "(1) Serial ",
            "(2) Parallel",
            "(3) Firewire ",
            "(4) USB",
            "(5) None of these",
            "19. Which is not an item of hardware? <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) An MP3 file ",
            "(2) A keyboard",
            "(3) A mouse ",
            "(4) Printer",
            "(5) None of these",
            "20. USB in data cables stands for<font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Unicode Smart Bus ",
            "(2) Universal Structural Bus",
            "(3) Unicode Serial Bus",
            "(4) Universal Smart Bus",
            "(5) Universal Serial Bus"
    };
    String[] answersSet4 = {"(2)", "(4)", "(2)", "(2)", "(2)", "(2)", "(3)", "(2)", "(2)", "(1)", "(5)", "(4)", "(2)", "(5)", "(5)", "(4)", "(1)", "(1)", "(1)", "(5)"

    };
    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }
}



