package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter1 {

    String[] questionsSet1 = {
            "1. The word computer has been derived from which of the following language?",
            "(1) Greek ",
            "(2) English",
            "(3) Hindi ",
            "(4) Latin",
            "(5) None of these",
            "2. Input, output and processing devices grouped together represent a(n)",
            "(1) mobile device",
            "(2) information processing cycle",
            "(3) circuit board",
            "(4) computer system",
            "(5) None of these",
            "3. Which of the following is the correct order of the four major functions of a computer?",
            "(1) Process, Output, Input, Storage",
            "(2) Input, Output, Process, Storage",
            "(3) Process, Storage, Input, Output",
            "(4) Input, Process, Output, Storage",
            "(5) None of these",
            "4. Collecting the data and converting it into information is called",
            "(1) processing",
            " (2) compiling",
            "(3) importing ",
            "(4) exporting",
            "(5) None of these",
            "5. Computer cannot perform",
            "(1) input ",
            "(2) output",
            "(3) thinking ",
            "(4) processing",
            "(5) None of these",
            "6. A computer cannot perform which of the following functions? <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) Addition ",
            "(2) Subtraction",
            "(3) Bake a cake ",
            "(4) Division",
            "(5) None of these",
            "7. Part number, description and number of parts ordered are examples of <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) control ",
            "(2) output",
            "(3) processing ",
            "(4) feedback",
            "(5) input",
            "8. Benefits of computers are",
            "(1) very fast and can store huge amount of data",
            "(2) provide accurate output either input is correct or not",
            "(3) think about the processing",
            "(4) All of the above",
            "(5) None of these",
            "9. A collection of unprocessed items is <font color=#0099ff>(SBI PO 2015)</font>",
            "(1) information ",
            "(2) data",
            "(3) memory ",
            "(4) reports",
            "(5) None of these",
            "10. Which among the following cycle consists of an input, processing, output and storage as its constituents? <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) Processing ",
            "(2) Output",
            "(3) Input ",
            "(4) Storage",
            "(5) Data",
            "11. ……… is data that has been organised and presented in a meaningful fashion. <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) A process ",
            "(2) Software",
            "(3) Storage ",
            "(4) Information",
            "(5) Data",
            "12. Data or information used to run the computer is called <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) hardware ",
            "(2) CPU",
            "(3) peripheral ",
            "(4) software",
            "(5) None of these",
            "13. The steps and tasks needed to process data, such as responses to questions or clicking an icon, are called <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) instructions",
            "(2) the operating system",
            "(3) application software",
            "(4) the system unit",
            "(5) the hardware unit",
            "14. The earliest calculating device is",
            "(1) calculator",
            "(2) abacus",
            "(3) difference engine",
            "(4) analytical engine",
            "(5) None of the above",
            "15. Abacus can perform",
            "(1) addition ",
            "(2) subtraction",
            "(3) multiplication ",
            "(4) Both ‘1’ and ‘2’",
            "(5) None of these",
            "16. The Napier’s technology used for calculation called",
            "(1) Naptologia ",
            "(2) Vibologia",
            "(3) Semiconductor ",
            "(4) Rabdologia",
            "(5) None of these",
            "17. Pascaline is also known by",
            "(1) abacus ",
            "(2) adding machine",
            "(3) division machine ",
            "(4) difference machine",
            "(5) None of these",
            "18. Punched cards were first introduced by",
            "(1) Powers ",
            "(2) Pascal",
            "(3) Jacquard ",
            "(4) Herman Hollerith",
            "(5) None of these",
            "19. Which of the following is known as father of computer?",
            "(1) Dennis Ritchie ",
            "(2) Napier",
            "(3) Charles Babbage ",
            "(4) Alan Turing",
            "(5) None of these",
            "20. Analytical Engine developed by",
            "(1) Blaise Pascal ",
            "(2) Charles Babbage",
            "(3) Dennis Ritchie ",
            "(4) Alan Turing",
            "(5) None of these",
    };
    String[] answersSet1 = {"(4)", "(4)", "(4)", "(1)", "(3)", "(3)", "(3)", "(1)", "(2)", "(5)", "(4)", "(5)", "(1)", "(2)", "(4)", "(4)", "(2)", "(3)", "(3)", "(2)"
    };

    String[] questionsSet2 = {
            "1. The Analytical Engine developed during first generation of computers used ......... as a memory unit. <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) RAM ",
            "(2) floppies",
            "(3) cards ",
            "(4) counter wheels",
            "(5) None of these",
            "2. Tabulating machine was the first electromechanical machine developed by",
            "(1) Herman Hollerith ",
            "(2) Howard Aiken",
            "(3) Blaise Pascal ",
            "(4) John Napier",
            "(5) None of these",
            "3. Who designed the first electronic computer-ENIAC?",
            "(1) Von Neumann",
            "(2) Joseph M Jacquard",
            "(3) Presper Eckert and John W Mauchly",
            "(4) All of the above",
            "(5) None of these",
            "4. The first computer which provides storage is <font color=#0099ff>(SSC CPO 2012)</font>",
            "(1) EDSAC ",
            "(2) EDVAC",
            "(3) MARK-I ",
            "(4) ACE",
            "(5) None of these",
            "5. Name the first general purpose electronic computer. <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) ADVAC ",
            "(2) ADSAC",
            "(3) UNIVAC",
            "(4) EDVAC",
            "(5) None of these",
            "6. Computer size was very large in",
            "(1) first generation ",
            "(2) second generation",
            "(3) third generation ",
            "(4) fourth generation",
            "(5) None of these",
            "7. First generation computers were based on",
            "(1) transistors ",
            "(2) conductors",
            "(3) ICs ",
            "(4) vacuum tubes",
            "(5) None of these",
            "8. Computer built before the first generation computer was",
            "(1) mechanical ",
            "(2) electromechanical",
            "(3) electrical ",
            "(4) electronics",
            "(5) None of these",
            "9. First generation computers used ......... languages. <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) machine ",
            "(2) assembly",
            "(3) Both ‘1’ and ‘2’ ",
            "(4) high level",
            "(5) None of these",
            "10. Speed of first generation computer was in <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) nano seconds ",
            "(2) milli seconds",
            "(3) nano-milli seconds ",
            "(4) micro seconds",
            "(5) None of these",
            "11. The period of the second generation computers was",
            "(1) 1946-1958 ",
            "(2) 1940-1960",
            "(3) 1956-63 ",
            "(4) 1957-1964",
            "(5) None of these",
            "12. Time sharing became possible in ......... generation of computers. <font color=#0099ff>(SBI PO 2011)</font>",
            "(1) first ",
            "(2) second ",
            "(3) third ",
            "(4) fourth",
            "(5) None of these",
            "13. Integrated Chips or IC’s were started to be use from which generation of computers? <font color=#0099ff>(IBPS PO 2016)</font>",
            "(1) 1st Generation ",
            "(2) 2nd Generation",
            "(3) 3rd Generation ",
            "(4) 4th Generation",
            "(5) 5th Generation",
            "14. Chip is a common nickname for a(n) <font color=#0099ff>(IBPS Clerk 2014, 15)</font>",
            "(1) transistor ",
            "(2) resistor",
            "(3) integrated circuit ",
            "(4) semiconductor",
            "(5) None of these",
            "15. The third generation computers were made with <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) bio chips ",
            "(2) transistors",
            "(3) integrated circuits ",
            "(4) vacuum tubes",
            "(5) discrete components",
            "16. Integrated Circuit (IC) or chips used in computers are made with <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) copper ",
            "(2) aluminium",
            "(3) gold ",
            "(4) silicon",
            "(5) silver",
            "17. A complete electronic circuit with transistors and other electronic components on a small silicon chip is called a(n) <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) workstation ",
            "(2) CPU",
            "(3) magnetic disc ",
            "(4) integrated circuit",
            "(5) complex circuit",
            "18. PCs are considered fourth-generation and contain <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) information",
            "(2) data",
            "(3) vacuum tubes",
            "(4) microprocessors",
            "(5) transistors",
            "19. Artificial Intelligence is an example of",
            "(1) first generation computer",
            "(2) second generation computer",
            "(3) third generation computer",
            "(4) fourth generation computer",
            "(5) fifth generation computer",
            "20. First computer of India is",
            "(1) PARAM ",
            "(2) Siddhartha",
            "(3) IBM-370 ",
            "(4) CRAY-1",
            "(5) None of these"  };
    String[] answersSet2 = {"(4)", "(1)", "(3)", "(1)", "(3)", "(1)", "(4)", "(2)", "(1)", "(4)", "(3)", "(2)", "(3)", "(3)", "(3)", "(4)", "(4)", "(4)", "(5)", "(2)"
    };

    String[] questionsSet3 = {
            "1. Computer’s basic architecture was developed by",
            "(1) John Von Neumann",
            "(2) Charles Babbage",
            "(3) Blaise Pascal",
            "(4) Jordan Murn",
            "(5) None of these",
            "2. Who developed integrated chip?",
            "(1) Robert Nayak ",
            "(2) C Babbage",
            "(3) JS Kilby ",
            "(4) CV Raman",
            "(5) None of these",
            "3. In latest generation computers, the instructions are executed",
            "(1) only parallel",
            "(2) only sequentially",
            "(3) Both ‘1’ and ‘2’",
            "(4) Either ‘1’ or ‘2’",
            "(5) None of these",
            "4. Microcomputer hardware consists of three basic categories of physical equipment",
            "(1) keyboard, monitor, hard drive",
            "(2) system unit, input/output, memory",
            "(3) system unit, input/output, secondary storage",
            "(4) system unit, primary storage, secondary storage",
            "(5) None of these",
            "5. Which of the following options correctly expresses the meaning of the term ‘PCs’? <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) Independent computers for all working staff",
            "(2) Personal computers widely available to individual workers with which they can access information from layer systems and increase their personal productivity",
            "(3) Packed computers system formed by joining together of various computer terminals",
            "(4) Computer manufactured by the Pentium Company",
            "(5) None of the above",
            "6. Which of the following is a small microprocessor based computer designed to be used by one person at a time? <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) Netbook ",
            "(2) Supercomputer",
            "(3) All-in-one ",
            "(4) Notebook",
            "(5) Personal computer",
            "7. Tablet PC is a type of",
            "(1) microcomputer ",
            "(2) supercomputer",
            "(3) minicomputer ",
            "(4) mainframe computer",
            "(5) None of these",
            "8. Computers that are portable and convenient to use for users who travel, are known as",
            "(1) supercomputers ",
            "(2) minicomputers",
            "(3) mainframe computers",
            "(4) laptops",
            "(5) None of these",
            "9. Desktop and personal computers are also known as <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) supercomputers ",
            "(2) servers",
            "(3) mainframes ",
            "(4) peripheral equipment",
            "(5) microcomputers",
            "10. Which of the following uses a handheld operating system? <font color=#0099ff>(SBI PO 2013)</font>",
            "(1) A supercomputer ",
            "(2) A personal computer",
            "(3) A laptop ",
            "(4) A mainframe",
            "(5) A PDA",
            "11. Palmtop computer is also known as",
            "(1) personal computer",
            "(2) notebook computer",
            "(3) tablet PC",
            "(4) handheld computer",
            "(5) None of these",
            "12. A central computer that holds collections of data and programs for many PCs, workstations and other computers is a",
            "(1) supercomputer ",
            "(2) minicomputer",
            "(3) laptop ",
            "(4) server",
            "(5) None of these",
            "13. Which computer is used for Computer Aided Design (CAD) calculations?",
            "(1) Minicomputer ",
            "(2) Mainframe computer",
            "(3) Supercomputer ",
            "(4) Microcomputer",
            "(5) None of these",
            "14. Which of the following is generally costlier? <font color=#0099ff>(SBI Clerk 2012, IBPS Clerk 2015)</font>",
            "(1) Server ",
            "(2) Notebook computer",
            "(3) Personal computer ",
            "(4) Laptop computer",
            "(5) Mainframe",
            "15. The user generally applies ......... to access mainframe or supercomputer.",
            "(1) terminal ",
            "(2) node",
            "(3) desktop ",
            "(4) handheld",
            "(5) None of these",
            "16. These are specially designed computers that perform complex calculations extremely rapidly.",
            "(1) Servers ",
            "(2) Supercomputers",
            "(3) Laptops ",
            "(4) Mainframes",
            "(5) None of these",
            "17. A ......... is a large and expensive computer capable of performing scientific and business applications.",
            "(1) supercomputer ",
            "(2) mainframe computer",
            "(3) minicomputer ",
            "(4) handheld computer",
            "(5) None of these",
            "18. First supercomputer developed in India is",
            "(1) PARAM ",
            "(2) CRAY-1",
            "(3) PARAM ISHAN ",
            "(4) EPRAM",
            "(5) None of these",
            "19. Pratyush is …… fastest supercomputer in the world.",
            "(1) first ",
            "(2) second",
            "(3) third ",
            "(4) fourth",
            "(5) None of these",
            "20. Pratyush supercomputer is dedicated for",
            "(1) multimedia ",
            "(2) weather forecasting",
            "(3) recreation ",
            "(4) military personnel",
            "(5) None of these"
    };
    String[] answersSet3 = {"(1)", "(3)", "(3)", "(2)", "(2)", "(5)", "(1)", "(4)", "(5)", "(5)", "(4)", "(4)", "(1)", "(5)", "(2)", "(2)", "(1)", "(1)", "(4)", "(2)"

    };
    String[] questionsSet4 = {
            "1. Which of the following is the India’s first multi-petaflops (PF) supercomputer?",
            "(1) PARAM ",
            "(2) Pratyush",
            "(3) PARAM Ishan ",
            "(4) Tianhe-2",
            "(5) None of these",
            "2. Analog computer works on the supply of",
            "(1) continuous electrical pulses",
            "(2) electrical pulses but not continuous",
            "(3) magnetic strength",
            "(4) physical strength",
            "(5) None of these",
            "3. Seismograph is an example of",
            "(1) Analog computer ",
            "(2) Digital computer",
            "(3) Hybrid computer ",
            "(4) All of thes",
            "(5) None of these",
            "4. These computers work by calculating the binary digits.",
            "(1) Hybrid ",
            "(2) Digital",
            "(3) Analog ",
            "(4) General purpose",
            "(5) None of these",
            "5. Choose the odd one out. <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) Microcomputer",
            "(2) Minicomputer",
            "(3) Supercomputer",
            "(4) Digital computer",
            "(5) Notebook computer",
            "6. A hybrid computer is the one having the combined properties of <font color=#0099ff>(SBI Clerk 2013)</font>",
            "(1) super and microcomputers",
            "(2) mini and microcomputers",
            "(3) analog and digital computers",
            "(4) super and mini computers",
            "(5) None of the above",
            "7. Which types of computer are used in hospitals like ECG and DIALYSIS?",
            "(1) Digital ",
            "(2) Hybrid",
            "(3) Analog ",
            "(4) Microcomputer",
            "(5) None of these",
            "8. General purpose computers are used for",
            "(1) creating a small database",
            "(2) performs calculation",
            "(3) accounting",
            "(4) All of the above",
            "(5) None of these",
            "9. Which is not the example of special purpose computer?",
            "(1) Automatic aircraft landing",
            "(2) Word processor",
            "(3) Multimedia computer",
            "(4) All of the above",
            "(5) None of these",
            "10. Which type of computer is used in automatic aircraft landing?",
            "(1) General computer",
            "(2) Supercomputer",
            "(3) Special purpose computer",
            "(4) Microcomputer",
            "(5) None of these",
            "11. Which of the following is the smallest and fastest computer imitating brain working? <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) Supercomputer",
            "(2) Quantum computer",
            "(3) Param-10000",
            "(4) IBM chips",
            "(5) None of these",
            "12. In which of the following computers are used?",
            "(1) Banking ",
            "(2) Education",
            "(3) Offices ",
            "(4) All of these",
            "(5) None of these",
            "13. It is the science that attempts to produce machines that display the same type of intelligence that humans do",
            "(1) Nano science",
            "(2) Nano technology",
            "(3) Simulation",
            "(4) Artificial Intelligence (AI)",
            "(5) None of these",
            "14. Which of the following deals with the design, construction, operation and use of robots?",
            "(1) Robotics ",
            "(2) Artificial Intelligence",
            "(3) Nano computer ",
            "(4) Quantum computer",
            "(5) None of these",
            "15. Punched cards were first introduced by",
            "(1) Powers ",
            "(2) Pascal",
            "(3) Jacquard ",
            "(4) Herman Hollerith",
            "(5) None of these",
            "16. Which of the following is known as father of computer?",
            "(1) Dennis Ritchie ",
            "(2) Napier",
            "(3) Charles Babbage ",
            "(4) Alan Turing",
            "(5) None of these",
            "17. Analytical Engine developed by",
            "(1) Blaise Pascal ",
            "(2) Charles Babbage",
            "(3) Dennis Ritchie ",
            "(4) Alan Turing",
            "(5) None of these",
            "18. PCs are considered fourth-generation and contain <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) information",
            "(2) data",
            "(3) vacuum tubes",
            "(4) microprocessors",
            "(5) transistors",
            "19. Artificial Intelligence is an example of",
            "(1) first generation computer",
            "(2) second generation computer",
            "(3) third generation computer",
            "(4) fourth generation computer",
            "(5) fifth generation computer",
            "20. First computer of India is",
            "(1) PARAM ",
            "(2) Siddhartha",
            "(3) IBM-370 ",
            "(4) CRAY-1",
            "(5) None of these"
             };
    String[] answersSet4 = {"(2)", "(1)", "(1)", "(2)", "(4)", "(3)", "(2)", "(4)", "(2)", "(3)", "(2)", "(4)", "(4)", "(1)" , "(3)", "(3)", "(2)","(4)", "(5)", "(2)"  };

    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }
}



