package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter11 {

    String[] questionsSet1 = {
            "1. ......... is the transmission of data between two or more computers over communication links.",
            "(1) Communication ",
            "(2) Networking",
            "(3) Data communication ",
            "(4) Data networking",
            "(5) None of these",
            "2. Communication channel having ......... types.",
            "(1) 1 ",
            "(2) 2 ",
            "(3) 3 ",
            "(4) 4",
            "(5) None of these",
            "3. In simplex channel, flow of data is",
            "(1) always in one direction",
            "(2) always in both direction",
            "(3) in both direction, but one at a time",
            "(4) All of the above",
            "(5) None of these",
            "4. Communication between a computer and a keyboard involves ........ transmission. <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) automatic ",
            "(2) half duplex",
            "(3) full-duplex ",
            "(4) simplex",
            "(5) None of these",
            "5. Mobile phone is an example of which type of communication channel?",
            "(1) Simplex ",
            "(2) Half duplex",
            "(3) Full duplex ",
            "(4) None of these",
            "(5) None of these",
            "6. Which of the following is not a property of twisted pair cabling?",
            "(1) Twisted pair cabling is a relatively low speed transmission",
            "(2) The wires can be shielded",
            "(3) The wires can be unshielded",
            "(4) Twisted pair cable carries signals as light waves",
            "(5) None of these",
            "7. In twisted pair, wires are twisted together, which are surrounded by an insulating material and an outer layer called",
            "(1) frame ",
            "(2) cover ",
            "(3) disk ",
            "(4) block",
            "(5) jacket",
            "8. Which of the following is the greatest advantage of co-axial cabling?",
            "(1) High security ",
            "(2) Physical dimensions",
            "(3) Long distances ",
            "(4) Easily tapped",
            "(5) None of these",
            "9. Which of the following cables can transmit data at high speeds? <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Flat cable ",
            "(2) Co-axial cable",
            "(3) Optic fibre cable ",
            "(4) Twisted pair cable",
            "(5) UTP cable",
            "10. Which of the following is an advantage for using fibre optics data transmission?",
            "(1) Resistance to data theft",
            "(2) Fast data transmission rate",
            "(3) Low noise level ",
            "(4) All of the above",
            "(5) None of these",
            "11. Networking using fibre optic cable is done as <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) it has high bandwidth",
            "(2) it is thin and light",
            "(3) it is not affected by electro magnetic interference/power surges etc",
            "(4) All of the above",
            "(5) None of these",
            "12. Which of the following is not a property of fibre optic cabling? <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) Transmits at faster speeds than copper cabling",
            "(2) Easier to capture a signal from the copper cabling",
            "(3) Very resistant to interference",
            "(4) Carries signals as light waves",
            "(5) less attenuation",
            "13. A device that connects to a network without the use of cables is said to be <font color=#0099ff>(IBPS Clerk 2012, RBI Grade B 2012)</font>",
            "(1) distributed ",
            "(2) cabled",
            "(3) centralised ",
            "(4) open source",
            "(5) wireless",
            "14. Which of the following is the fastest communication channel?",
            "(1) Radio wave ",
            "(2) Microwave",
            "(3) Optical fibre",
            "(4) All are operating at nearly the same propagation speed",
            "(5) None of these",
            "15. Bandwidth refers to <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) the cost of the cable required to implement a WAN",
            "(2) the cost of the cable required to implement a LAN",
            "(3) the amount of information a peer-to-peer network can store",
            "(4) the amount of information a communication medium can transfer in a given amount of time",
            "(5) None of the above",
            "16. Which of the following represents the fastest data transmission speed? <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) Bandwidth ",
            "(2) bps",
            "(3) gbps ",
            "(4) kbps",
            "(5) mbps",
            "17. A(n) ......... is composed of several computers connected together to share resources and data. <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) Internet ",
            "(2) Network",
            "(3) Backbone ",
            "(4) Hyperlink",
            "(5) Protocol",
            "18. What do we call for the arrangement when two or more computers physically connected by cables to share information or hardware? <font color=#0099ff>(SBI Clerk 2015)</font>",
            "(1) URL ",
            "(2) Network",
            "(3) Server ",
            "(4) Internet",
            "(5) Modem",
            "19. A combination of hardware and software that allows communication and electronic transfer of information between computers is a <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) network ",
            "(2) backup system",
            "(3) server ",
            "(4) peripheral",
            "(5) modem",
            "20. Which of the following terms is associated with networks? <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) MS-Excel ",
            "(2) Mouse",
            "(3) Word ",
            "(4) Connectivity",
            "(5) Plotter",
    };
    String[] answersSet1 = {
            "(3)","(3)","(1)","(4)","(3)","(4)","(5)","(2)","(3)","(3)","(4)","(3)","(5)","(2)","(4)","(3)","(2)","(2)","(1)","(4)",

    };
    String[] questionsSet2 = {
            "1. What type of resource is most likely to be a shared common resource in a computer network? <font color=#0099ff>(Allahabad Bank Clerk 2010)</font>",
            "(1) Printers ",
            "(2) Speakers",
            "(3) Floppy disk drives ",
            "(4) Keyboards",
            "(5) None of these",
            "2. The first network that has planted the seeds of Internet was",
            "(1) ARPANET ",
            "(2) NSFnet",
            "(3) V-net ",
            "(4) I-net",
            "(5) None of these",
            "3. Pathways that support communication among the various electronic components on the system board are called <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) network lines ",
            "(2) processors",
            "(3) logic paths ",
            "(4) bus lines",
            "(5) gateway",
            "4. What do we call a network whose elements may be separated by some distance? It usually involves two or more network and dedicated high speed telephone lines. <font color=#0099ff>(SBI Clerk 2015)</font>",
            "(1) LAN ",
            "(2) WAN",
            "(3) URL ",
            "(4) Server",
            "(5) World Wide Web",
            "5. LAN can use ......... architecture.",
            "(1) peer-to-peer ",
            "(2) client and server",
            "(3) Both ‘1’ and ‘2’ ",
            "(4) Neither ‘1’ nor ‘2’",
            "(5) None of these",
            "6. Ethernet, token ring and token bus are types of <font color=#0099ff>(SBI Associates 2012, RBI Grade B 2014)</font>",
            "(1) WAN",
            "(2) LAN",
            "(3) communication channels",
            "(4) physical media",
            "(5) None of the above",
            "7. The advantage of LAN is <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) sharing peripherals",
            "(2) backing up your data",
            "(3) saving all your data",
            "(4) accessing the Web",
            "(5) automatic printing of data",
            "8. Computer connected to a LAN can ……… . <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) run faster",
            "(2) share information and/or share peripheral equipment",
            "(3) go online",
            "(4) E-mail",
            "(5) None of the above",
            "9. ......... allows LAN users to share computer programs and data.",
            "(1) Communication server",
            "(2) Print server",
            "(3) File server",
            "(4) All of the above",
            "(5) None of these",
            "10. What is the use of bridge in network?",
            "(1) To connect LANs",
            "(2) To separate LANs",
            "(3) To control network speed",
            "(4) All of the above",
            "(5) None of these",
            "11. Which of the following items is not used in Local Area Network (LANs)? <font color=#0099ff>(SSC CGL 2012)</font>",
            "(1) Interface card ",
            "(2) Cable",
            "(3) Computer ",
            "(4) Modem",
            "(5) None of these",
            "12. Which type of network would use phone lines? <font color=#0099ff>(SBI Clerk 2012, IBPS Clerk 2015)</font>",
            "(1) WAN ",
            "(2) LAN",
            "(3) WWAN ",
            "(4) Wireless",
            "(5) None of these",
            "13. Which of the following refers to a small, single-site network?",
            "(1) PAN ",
            "(2) DSL ",
            "(3) RAM ",
            "(4) USB",
            "(5) CPU",
            "14. These servers store and manage files for network users.",
            "(1) Authentication ",
            "(2) Main",
            "(3) Web ",
            "(4) File",
            "(5) None of these",
            "15. ……… is the most important/powerful computer in a typical network. <font color=#0099ff>(SBI PO 2013)</font>",
            "(1) Desktop ",
            "(2) Network client",
            "(3) Network server ",
            "(4) Network station",
            "(5) Network switch",
            "16. A protocol is a set of rules governing a time sequence of events that must take place",
            "(1) between peers ",
            "(2) between an interface",
            "(3) between modems ",
            "(4) across an interface",
            "(5) None of these",
            "17. A ……… is an agreement between the communication parties on how communication is to proceed.<font color=#0099ff>(SSC CGL 2016)</font>",
            "(1) path ",
            "(2) SLA",
            "(3) bond ",
            "(4) protocol",
            "(5) None of these",
            "18. A device operating at the physical layer is called a",
            "(1) bridge ",
            "(2) router",
            "(3) repeater ",
            "(4) All of these",
            "(5) None of these",
            "19. Which of the following devices that joins multiple computers together within one LAN?",
            "(1) Repeater ",
            "(2) Hub",
            "(3) Gateway ",
            "(4) Switch",
            "(5) Router",
            "20. Which of the following is used for modulation and demodulation?",
            "(1) Modem ",
            "(2) Protocols",
            "(3) Gateway ",
            "(4) Multiplexer",
            "(5) None of these",
    };
    String[] answersSet2 = {
            "(3)","(3)","(1)","(4)","(3)","(4)","(5)","(2)","(3)","(3)","(4)","(3)","(5)","(2)","(4)","(3)","(2)","(2)","(1)","(4)"

    };
    String[] questionsSet3 = {
            "1. What is the name of the derive that links your computer with other computers and information services through telephone lines? <font color=#0099ff>(SBI Clerk 2015)</font>",
            "(1) Modem ",
            "(2) LAN ",
            "(3) URL ",
            "(4) WAN",
            "(5) Server",
            "2. What is the function of a modem? <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) Encryption and decryption",
            "(2) Converts data to voice and vice- versa",
            "(3) Converts analog signals to digital signals and vice-versa",
            "(4) Serves as a hardware antivirus",
            "(5) None of the above",
            "3. The hardware device or software program that sends messages between network is known as a <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) bridge ",
            "(2) backbone ",
            "(3) router ",
            "(4) gateway",
            "(5) Other than those given as options",
            "4. Which of the following is not a network device?",
            "(1) Router ",
            "(2) Switch ",
            "(3) Bus ",
            "(4) Bridge",
            "(5) None of these",
            "5. Geometric arrangement of devices on the network is called",
            "(1) topology ",
            "(2) protocols",
            "(3) media ",
            "(4) LAN",
            "(5) None of these",
            "6. Which of the following topologies is not of broadcast type?",
            "(1) Star ",
            "(2) Bus",
            "(3) Ring ",
            "(4) All of these",
            "(5) None of these",
            "7. Network components are connected to the same cable in the ......... topology.",
            "(1) star ",
            "(2) ring ",
            "(3) bus ",
            "(4) mesh",
            "(5) tree",
            "8. Hub is associated with ……… network. <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) bus ",
            "(2) ring",
            "(3) star ",
            "(4) mesh",
            "(5) All of these",
            "9. In a ring topology, the computer in possession of the ......... can transmit data.",
            "(1) packet ",
            "(2) data",
            "(3) access method ",
            "(4) token",
            "(5) None of these",
            "10. In which topology, every node is connected to two other nodes? <font color=#0099ff>(IBPS RRB PO Mains 2018)</font>",
            "(1) Bus topology ",
            "(2) ring topology",
            "(3) Star topology ",
            "(4) Mesh topology",
            "(5) None of these",
            "11. Which is the name of the network topology in which there are bi-directional links between each possible node? <font color=#0099ff>(SSC CGL 2012)</font>",
            "(1) Ring ",
            "(2) Star ",
            "(3) Tree ",
            "(4) Mesh",
            "(5) None of these",
            "12. An alternate name for the completely interconnected network topology is <font color=#0099ff>(SSC CGL 2012)</font>",
            "(1) mesh ",
            "(2) star",
            "(3) tree ",
            "(4) ring",
            "(5) None of these",
            "13. Which is the highest reliability topology? <font color=#0099ff>(IBPS RRB PO Mains 2018)</font>",
            "(1) Mesh topology ",
            "(2) Tree topology",
            "(3) Bus topology ",
            "(4) Star topology",
            "(5) None of these",
            "14. P2P is a ......... application architecture. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) client/server ",
            "(2) distributed",
            "(3) centralised ",
            "(4) 1-tier",
            "(5) None of these",
            "15. A packet filtering firewall operates at which of the following OSI layers?",
            "(1) At the application layer",
            "(2) At the transport layer",
            "(3) At the network layer",
            "(4) At the gateway layer",
            "(5) None of these",
            "16. Encryption and decryption are the functions of",
            "(1) transport layer ",
            "(2) session layer",
            "(3) presentation layer ",
            "(4) All of these",
            "(5) None of these",
            "17. Name the fourth layer of OSI model <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) Application layer",
            "(2) Data link layer",
            "(3) Transport layer",
            "(4) Session layer",
            "(5) None of these",
            "18. In OSI network architecture, the routing is performed by <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) Network layer ",
            "(2) Data link layer",
            "(3) Transport layer ",
            "(4) Session layer",
            "(5) None of these",
            "19. In the following list of devices which device is used in network layer? <font color=#0099ff>(SSC CGL 2016)</font>",
            "(1) Repeaters",
            "(2) Router",
            "(3) Application Gateway",
            "(4) Switch",
            "(5) None of these",
            "20. Switches work on which OSI layer?",
            "(1) Data link layer",
            "(2) Physical layer",
            "(3) Transport layer",
            "(4) Network layer",
            "(5) Application layer",
    };
    String[] answersSet3 = {
            "(1)","(3)","(5)","(3)","(1)","(2)","(3)","(3)","(4)","(2)","(4)","(1)","(1)","(1)","(1)","(3)","(3)","(1)","(2)","(1)",

    };
    String[] questionsSet4 = {
            "1. In IT networking, which of the following device is used in physical layer? <font color=#0099ff>(SSC CGL 2016)</font>",
            "(1) Repeater ",
            "(2) Router",
            "(3) Transport Gateway ",
            "(4) Bridge",
            "(5) None of these",
            "2. Multiplexing involves ……… path(s) and ……… channel(s). <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) one, one ",
            "(2) one, multiple",
            "(3) multiple, one ",
            "(4) multiple, multiple",
            "(5) None of these",
            "3. A processor that collects the transmissions from several communication media and send them over a single line that operates at a higher capacity is called <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) multiplexer ",
            "(2) bridge",
            "(3) hub ",
            "(4) router",
            "(5) None of these",
            "4. To send data/message to and from computers, the network software puts the message information in a",
            "(1) NIC ",
            "(2) packet ",
            "(3) trailer ",
            "(4) header",
            "(5) None of these",
            "5. How many bits are there in the ethernet address? <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) 64 bits ",
            "(2) 48 bits ",
            "(3) 32 bits ",
            "(4) 16 bits",
            "(5) None of these",
            "6. Ethernet uses",
            "(1) bus topology ",
            "(2) ring topology",
            "(3) mesh topology ",
            "(4) All of these",
            "(5) None of these",
            "7. In networks, a small message used to pass between one station to another is known as <font color=#0099ff>(SSC CGL 2016)</font>",
            "(1) Token ",
            "(2) Byte ",
            "(3) Word ",
            "(4) Ring",
            "(5) None of these",
            "8. Computer connected to a LAN can ……… . <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) run faster",
            "(2) share information and/or share peripheral equipment",
            "(3) go online",
            "(4) E-mail",
            "(5) None of the above",
            "9. ......... allows LAN users to share computer programs and data.",
            "(1) Communication server",
            "(2) Print server",
            "(3) File server",
            "(4) All of the above",
            "(5) None of these",
            "10. What is the use of bridge in network?",
            "(1) To connect LANs",
            "(2) To separate LANs",
            "(3) To control network speed",
            "(4) All of the above",
            "(5) None of these",
            "11. Which of the following items is not used in Local Area Network (LANs)? <font color=#0099ff>(SSC CGL 2012)</font>",
            "(1) Interface card ",
            "(2) Cable",
            "(3) Computer ",
            "(4) Modem",
            "(5) None of these",
            "12. Which type of network would use phone lines? <font color=#0099ff>(SBI Clerk 2012, IBPS Clerk 2015)</font>",
            "(1) WAN ",
            "(2) LAN",
            "(3) WWAN ",
            "(4) Wireless",
            "(5) None of these",
            "13. Which of the following refers to a small, single-site network?",
            "(1) PAN ",
            "(2) DSL ",
            "(3) RAM ",
            "(4) USB",
            "(5) CPU",
            "14. These servers store and manage files for network users.",
            "(1) Authentication ",
            "(2) Main",
            "(3) Web ",
            "(4) File",
            "(5) None of these",
            "15. ……… is the most important/powerful computer in a typical network. <font color=#0099ff>(SBI PO 2013)</font>",
            "(1) Desktop ",
            "(2) Network client",
            "(3) Network server ",
            "(4) Network station",
            "(5) Network switch",
            "16. A protocol is a set of rules governing a time sequence of events that must take place",
            "(1) between peers ",
            "(2) between an interface",
            "(3) between modems ",
            "(4) across an interface",
            "(5) None of these",
            "17. A ……… is an agreement between the communication parties on how communication is to proceed.<font color=#0099ff>(SSC CGL 2016)</font>",
            "(1) path ",
            "(2) SLA",
            "(3) bond ",
            "(4) protocol",
            "(5) None of these",
            "18. A device operating at the physical layer is called a",
            "(1) bridge ",
            "(2) router",
            "(3) repeater ",
            "(4) All of these",
            "(5) None of these",
            "19. Which of the following devices that joins multiple computers together within one LAN?",
            "(1) Repeater ",
            "(2) Hub",
            "(3) Gateway ",
            "(4) Switch",
            "(5) Router",
            "20. Which of the following is used for modulation and demodulation?",
            "(1) Modem ",
            "(2) Protocols",
            "(3) Gateway ",
            "(4) Multiplexer",
            "(5) None of these"
    };
    String[] answersSet4 = {
            "(1)","(2)","(1)","(2)","(2)","(1)","(1)","(2)","(3)","(3)","(4)","(3)","(5)","(2)","(4)","(3)","(2)","(2)","(1)","(4)"


    };

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }

    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }
}



