package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter12 {


    String[] questionsSet1 = {
            "1. The vast network of computers that connects millions of people all over the world is called",
            "(1) LAN ",
            "(2) Web",
            "(3) Hypertext ",
            "(4) Internet",
            "(5) None of these",
            "2. The Internet is a system of",
            "(1) software bundles ",
            "(2) web page",
            "(3) website",
            "(4) interconnected networks",
            "(5) None of these",
            "3. The Internet is",
            "(1) a large network of networks",
            "(2) an internal communication system for a business",
            "(3) a communication system for the Indian government",
            "(4) All of the above",
            "(5) None of these",
            "4. The Internet allows to",
            "(1) send electronic mail ",
            "(2) view Web pages",
            "(3) connect to servers all around the world",
            "(4) All of the above",
            "(5) None of these",
            "5. Which of the following is an example of connectivity?",
            "(1) Internet ",
            "(2) Floppy disk",
            "(3) Power cord ",
            "(4) Data",
            "(5) None of these",
            "6. Internet was developed in the",
            "(1) 1950s ",
            "(2) 1960s ",
            "(3) 1970s ",
            "(4) 1980s",
            "(5) 1990s",
            "7. Which of the following is not a type of broadband Internet connection?",
            "(1) Cable ",
            "(2) DSL ",
            "(3) Dial-up ",
            "(4) BPL",
            "(5) None of these",
            "8. What does the acronym ISP stand for? <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) Internal Service Provider",
            "(2) International Service Provider",
            "(3) Internet Service Provider",
            "(4) Internet Service Providing",
            "(5) Internet Service Provision",
            "9. Your business has contracted with another company to have them host and run an application for your company over the Internet. The company providing this service to your business is called an",
            "(1) Internet Service Provider",
            "(2) Internet Access Provider",
            "(3) Application Service Provider",
            "(4) Application Access Provider",
            "(5) None of these",
            "10. DSL is an example of which connection?",
            "(1) Network ",
            "(2) Wireless",
            "(3) Slow ",
            "(4) Broadband",
            "(5) None of these",
            "11. ……… networks can be used for public internet access at hotspot such as restaurants, coffee shops etc.",
            "(1) Wi-Fi ",
            "(2) WiMax",
            "(3) DSL ",
            "(4) BPL",
            "(5) None of these",
            "12. A programme, either talk numeric that is made available in digital format for automatic download over the Internet is called ……… . <font color=#0099ff>(IBPS Clerk 2013 Or RRB PO Mains 2018)</font>",
            "(1) vodcast ",
            "(2) blog ",
            "(3) podcast ",
            "(4) wiki",
            "(5) broadcast",
            "13. A protocol is a set of rules that consists of",
            "(1) TCD/IT ",
            "(2) TCP/IP",
            "(3) TCP/IT ",
            "(4) TCT/IP",
            "(5) None of these",
            "14. The standard protocol of the Internet is",
            "(1) TCP/IP ",
            "(2) Java ",
            "(3) HTML ",
            "(4) flash",
            "(5) None of these",
            "15. In computing, IP address means",
            "(1) International Pin ",
            "(2) Internet Protocol",
            "(3) Invalid Pin ",
            "(4) Insert Pin",
            "(5) None of these",
            "16. Each IP packet must contain <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) only source address ",
            "(2) only destination address",
            "(3) source and destination addresses",
            "(4) source or destination address",
            "(5) None of the above",
            "17. IPv4 address is <font color=#0099ff>(IBPS PO 2013)</font> Or An IP address is ……… bit number <font color=#0099ff>(SSC CGL 2017)</font>",
            "(1) 8 bit ",
            "(2) 16 bit ",
            "(3) 32 bit ",
            "(4) 64 bit",
            "(5) None of these",
            "18. FTP can transfer files between any computers that have an Internet connection. Here, FTP stands for",
            "(1) File Transfer Protocol",
            "(2) Fast Text Processing",
            "(3) File Transmission Program",
            "(4) Fast Transmission Processor",
            "(5) None of these",
            "19. Which of the following is the communication protocol that sets the standard used by every computer that accesses Web-based information?",
            "(1) XML ",
            "(2) DML <font color=#0099ff>(SBI PO 2010)</font>",
            "(3) HTTP ",
            "(4) HTML",
            "(5) None of these",
            "20. What is the full form of HTTP? <font color=#0099ff>(IBPS Clerk 2014)</font>",
            "(1) HyperText Transfer Protocol",
            "(2) HyperText Transition Protocol",
            "(3) HyperText Transfer Program",
            "(4) HyperText Transition Program",
            "(5) HyperText Trivial Protocol"
    };
    String[] answersSet1 = {
            "(4)","(4)","(4)","(4)","(1)","(1)","(3)","(3)","(1)","(4)","(1)","(3)","(2)","(1)","(2)","(3)","(3)","(1)","(3)","(1)"

    };
    String[] questionsSet2 = {
            "1. An HTTP request contains ……… parts.",
            "(1) 1 ",
            "(2) 5 ",
            "(3) 3 ",
            "(4) 4",
            "(5) 2",
            "2. Documents converted to ......... can be published to the Web. <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) a doc file",
            "(2) http",
            "(3) Other than those given as options",
            "(4) machine language",
            "(5) HTML",
            "3. Documents converted to……can be published to the Web.",
            "(1) .doc file ",
            "(2) http",
            "(3) machine language ",
            "(4) HTML",
            "(5) None of these",
            "4. HTML is used for designing Web pages. Here, HTML stands for Or The web uses the ……… to request and serve web pages and programs. <font color=#0099ff>(SSC CGL 2017)</font>",
            "(1) High Transfer Machine Language",
            "(2) High Transmission Markup Language",
            "(3) HyperText Markup Language",
            "(4) Hyper Transfer Markup Language",
            "(5) None of these",
            "5. Which of the following is required to create an HTML document? <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) Browser ",
            "(2) Internet",
            "(3) Text editor ",
            "(4) Search engine",
            "(5) None of these",
            "6. In HTML, tags consists of keywords enclosed within <font color=#0099ff>(SSC CHSL 2013)</font>",
            "(1) flower brackets",
            "(2) angular brackets <>",
            "(3) parentheses ()",
            "(4) square brackets ",
            "(5) None of these",
            "7. Telnet is a <font color=#0099ff>(SSC CHSL 2012)</font>",
            "(1) search engine ",
            "(2) browser",
            "(3) protocol ",
            "(4) gateway",
            "(5) None of these",
            "8. Telnet is a ......... based computer protocol. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) sound ",
            "(2) text",
            "(3) image ",
            "(4) animation",
            "(5) digits",
            "9. Through ………, an administrator or another user can access someone else’s computer remotely. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) administrator ",
            "(2) Web server",
            "(3) Web application ",
            "(4) http",
            "(5) telnet",
            "10. The ……… service allows a group of Internet users to exchange their views on some common topic.",
            "(1) nicnet ",
            "(2) milnet ",
            "(3) telnet ",
            "(4) usenet",
            "(5) None of these",
            "11. Which protocol provides E-mail facility among different hosts? <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) SMTP ",
            "(2) FTP",
            "(3) TELNET ",
            "(4) SNMP",
            "(5) None of these",
            "12. What is the full form of VolP?",
            "(1) Voice of Internet Power",
            "(2) Voice over Internet Protocol",
            "(3) Voice on Internet Protocol",
            "(4) Very Optimised Internet Protocol",
            "(5) None of these",
            "13. The Internet service that provides a multimedia interface to available resources is called",
            "(1) FTP ",
            "(2) world wide web",
            "(3) telnet ",
            "(4) gopher",
            "(5) None of these",
            "14. WWW stands for <font color=#0099ff>(IBPS Clerk 2013, 2014)</font>",
            "(1) World Wide Wizard",
            "(2) World Wide Web",
            "(3) World Wide Wonder ",
            "(4) Wide World Web",
            "(5) None of these",
            "15. The ………… uses an addressing scheme known as URL indicate the location of files on the web. <font color=#0099ff>(SSC CGL 2017)</font>",
            "(1) java script ",
            "(2) World Wide Web",
            "(3) SQL ",
            "(4) String",
            "(5) None of these",
            "16. The WWW is made up of the set of interconnected ......... that are linked together over the Internet.",
            "(1) electronic documents",
            "(2) Web pages",
            "(3) files",
            "(4) All of these",
            "(5) None of these",
            "17. What is a Website? <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) A place from where we can get information in documents and files",
            "(2) A site that is owned by any particular company",
            "(3) A location on the world wide web",
            "(4) A place from where we can access Internet",
            "(5) None of the above",
            "18. A Website address is a unique name that identifies a specific ......... on the Web. <font color=#0099ff>(SBI PO 2010)</font>",
            "(1) Web browser ",
            "(2) Website",
            "(3) PDA ",
            "(4) link",
            "(5) None of these",
            "19. A (n) ……… appearing on a Web page opens another document when clicked.",
            "(1) anchor ",
            "(2) URL ",
            "(3) hyperlink ",
            "(4) reference",
            "(5) heading",
            "20. A reference to data that reader can directly follow by selecting or hovering is",
            "(1) hypertext ",
            "(2) hyperlink",
            "(3) hyper media ",
            "(4) hyper markup",
            "(5) None of these"
    };
    String[] answersSet2 = {
            "(3)","(5)","(4)","(3)","(3)","(2)","(3)","(2)","(5)","(4)","(1)","(2)","(2)","(2)","(2)","(2)","(3)","(2)","(3)","(2)"

    };
    String[] questionsSet3 = {
            "1. A Website is collection of <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) graphics ",
            "(2) programs",
            "(3) algorithms ",
            "(4) Web pages",
            "(5) charts",
            "2. ……… is collection of Web pages and ……… is the very first page that we seen on opening of Website.",
            "(1) Home page, Web page",
            "(2) Website, home page",
            "(3) Web page, home page",
            "(4) Web page, Website",
            "(5) None of the above",
            "3. A browser is a <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) tool for creating a database",
            "(2) software program to view Web pages on the Internet",
            "(3) printing device",
            "(4) software program to delete a folder",
            "(5) None of the above",
            "4. Conference (Netscape), Netmeeting (Internet Explorer) enables (choose the option that best describes) <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) sharing voice on the net",
            "(2) live textual conferencing",
            "(3) live audio conferencing",
            "(4) live real time conferencing",
            "(5) None of the above",
            "5. To view information on the Web you must have a <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) cable modem ",
            "(2) Web browser",
            "(3) domain name server ",
            "(4) hypertext viewer",
            "(5) None of the above",
            "6. A ……… is a software program used to view Web pages. <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) site ",
            "(2) host ",
            "(3) link ",
            "(4) browser",
            "(5) None of these",
            "7. Which one of the following is used to browse and search for information on the Internet?",
            "(1) Eudora ",
            "(2) Netscape ",
            "(3) FTP ",
            "(4) Telnet",
            "(5) None of these",
            "8. The ……… which contains billions of documents called Web pages, is one of the more popular services on the Internet. <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) Web server ",
            "(2) telnet",
            "(3) Web ",
            "(4) collection",
            "(5) None of these",
            "9. What is URL? <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) A computer software program",
            "(2) A type of programming object",
            "(3) The address of a document or ‘page’ on the world wide web",
            "(4) An acronym for unlimited resource for learning",
            "(5) A piece of hardware",
            "10. Which of the following is used by the browser to connect to the location of the Internet resources? <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) Linkers ",
            "(2) Protocol ",
            "(3) Cable ",
            "(4) URL",
            "(5) None of these",
            "11. An absolute ……… contains the complete address of a file on the nternet. <font color=#0099ff>(SSC CGL 2017)</font>",
            "(1) JavaScript ",
            "(2) URL",
            "(3) SQL ",
            "(4) String",
            "(5) None of these",
            "12. Which of the following must be contained in a URL? <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) A protocol identifier",
            "(2) The letters, WWW",
            "(3) The unique registered domain name",
            "(4) WWW and the unique registered domain name",
            "(5) A protocol identifier, WWW and the unique registered domain name",
            "13. URL identifies the location of a specific Web page on the Internet. Here URL stands for",
            "(1) Uniform Read Locator",
            "(2) Uniform Resource Locator",
            "(3) Unicode Research Location",
            "(4) United Research Locator",
            "(5) None of the above",
            "14. Which among the following term means/refers to web address of a page?",
            "(1) SMTP ",
            "(2) IP ",
            "(3) HTTP ",
            "(4) URL",
            "(5) MAC",
            "15. The last three letters of the domain name describes the type of <font color=#0099ff>(SSC FCI 2012)</font>",
            "(1) organisation (domain name)",
            "(2) connectivity",
            "(3) server",
            "(4) protocol",
            "(5) None of these",
            "16. An educational institution would generally have the following in its domain name. <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) .org ",
            "(2) .edu ",
            "(3) .inst ",
            "(4) .com",
            "(5) .sch",
            "17. Which of the following domains is used by profit business? <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) .com ",
            "(2) .edu ",
            "(3) .mil ",
            "(4) .net",
            "(5) .org",
            "18. Specialised programs that assist users in locating information on the Web are called <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) information engines",
            "(2) locator engines",
            "(3) Web browsers",
            "(4) resource locators",
            "(5) search engines",
            "19. Which of the following forms a part of a search engine?",
            "(1) Spiders of Web crawlers",
            "(2) Indexing software",
            "(3) Search algorithm ",
            "(4) All of the above",
            "(5) None of these",
            "20. Which among the following is a search engine?",
            "(1) Internet Explorer ",
            "(2) Flash",
            "(3) Google ",
            "(4) Firefox",
            "(5) None of these"
    };
    String[] answersSet3 = {
            "(4)","(2)","(2)","(4)","(2)","(4)","(2)","(1)","(3)","(4)","(2)","(5)","(2)","(4)","(1)","(2)","(1)","(5)","(1)","(3)"

    };
    String[] questionsSet4 = {
            "1. A ……… is the term used when a search engine returns a Web page that matches the search criteria. <font color=#0099ff>(IBPS PO 2011)</font>",
            "(1) blog ",
            "(2) hit ",
            "(3) link ",
            "(4) view",
            "(5) success",
            "2. Which is not the feature of Internet?",
            "(1) E-mail ",
            "(2) Newsgroup",
            "(3) Chat ",
            "(4) Designing",
            "(5) None of these",
            "3. Which among the following is an area of e-mail that is short description of the message?",
            "(1) Subject ",
            "(2) Cc",
            "(3) Bcc ",
            "(4) Attachment",
            "(5) Spam",
            "4. Which of the following is always a part of E-mail address?",
            "(1) Period (.) ",
            "(2) At sign (@)",
            "(3) Space () ",
            "(4) Underscore (_)",
            "(5) Angular Bracket (<)",
            "5. An e-mail attachment is referred to as",
            "(1) The body of the e-mail",
            "(2) The address of the sender",
            "(3) A document that is sent with an e-mail.",
            "(4) The address of the receiver",
            "(5) Any document that can be attached and sent with an e-mail",
            "6. Which one of the following is not an e-mail service provider?",
            "(1) Hotmail ",
            "(2) Gmail",
            "(3) Bing ",
            "(4) Yahoo mail",
            "(5) Outlook",
            "7. Which of the following fields of an e-mail hides the identity of the recipients?",
            "(1) To ",
            "(2) From ",
            "(3) Cc ",
            "(4) Bcc",
            "(5) None of these",
            "8. Sending an E-mail is similar to",
            "(1) writing a letter ",
            "(2) drawing a picture",
            "(3) talking on the phone",
            "(4) sending a package",
            "(5) None of the above",
            "9. Junk e-mail is also called <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) crap ",
            "(2) spoof",
            "(3) sniffer script ",
            "(4) spool",
            "(5) spam",
            "10. What can possible be the drawback of e-mails?",
            "(1) E-mails require being physically delivered to the user",
            "(2) E-mails infect computer",
            "(3) E-mails are very expensive to transmit",
            "(4) E-mails are slow to load",
            "(5) People don’t check e-mails regularly",
            "11. Which of the following is a valid e-mail address?",
            "(1) name. Website@info@ed",
            "(2) name. Website@info.in",
            "(3) name. @Website.info.com",
            "(3) Website. name@website.com",
            "(5) Website@info.com",
            "12. What is included in an E-mail address? <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) Domain name followed by user’s name",
            "(2) User’s name followed by domain name",
            "(3) User’s name followed by postal address",
            "(4) User’s name followed by street address",
            "(5) None of the above",
            "13. Which of the following elements are used in an e-mail to express emotions or feelings clearly?",
            "(1) Acronyms ",
            "(2) Abbreviations",
            "(3) Rich text ",
            "(4) Emoticons or smileys",
            "(5) None of these",
            "14. If you receive an E-mail from someone you don’t know, what should you do?",
            "(1) Forward it to the police immediately",
            "(2) Delete it without opening it",
            "(3) Open it and respond to them saying you don’t know them",
            "(4) Reply and ask them for their personal information",
            "(5) None of these",
            "15. Which of the following cannot be part of an E-mail address?",
            "(1) Period (.) ",
            "(2) At Sign (@)",
            "(3) Space () ",
            "(4) Underscore (_)",
            "(5) None of these",
            "16. Gmail belongs to",
            "(1) great mail ",
            "(2) yahoo mail",
            "(3) google mail ",
            "(4) gopher mail",
            "(5) None of these",
            "17. Which of the following is not a term pertaining to E-mail? <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) PowerPoint ",
            "(2) Inbox",
            "(3) Sender ",
            "(4) Receiver",
            "(5) None of the above",
            "18. Storage area for E-mail messages is called",
            "(1) folder ",
            "(2) file",
            "(3) mail box ",
            "(4) directory",
            "(5) None of these",
            "19. An E-mail address typically consists of a user ID followed by the………sign and the domain name that manages the user’s electronic post office box.",
            "(1) # ",
            "(2) @ ",
            "(3) & ",
            "(4) $",
            "(5) None of these",
            "20. Video conferencing is used for",
            "(1) talking each other",
            "(2) communicating purpose",
            "(3) live conversation",
            "(4) All of the above",
            "(5) None of these"
    };
    String[] answersSet4 = {
            "(2)","(4)","(1)","(2)","(5)","(3)","(4)","(1)","(5)","(2)","(3)","(2)","(4)","(2)","(3)","(3)","(1)","(3)","(2)","(4)"

    };

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }

    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }
}



