package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter10 {

    String[] questionsSet1 = {
            "1. A computer checks the …… of username and password for a match before granting access. <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) website ",
            "(2) network",
            "(3) backup file ",
            "(4) database",
            "(5) None of these",
            "2. A ......... is a collection of data that is stored electronically as a series of records in a table.",
            "(1) spreadsheet ",
            "(2) presentation",
            "(3) database ",
            "(4) Web page",
            "(5) None of these",
            "3. A collection of interrelated records is called a <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) utility file",
            "(2) management information system",
            "(3) database",
            "(4) spreadsheet",
            "(5) datasheet",
            "4. Which of the following is the organised collection of large amount of interrelated data stored in a meaningful way used for manipulation and updating? <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) Database ",
            "(2) File",
            "(3) Folder ",
            "(4) Data-mining",
            "(5) Data source",
            "5. Items such as names and addresses are considered as",
            "(1) input ",
            "(2) data ",
            "(3) output ",
            "(4) records",
            "(5) None of these",
            "6. Which type of database, organised the data in the form of tree with nodes?",
            "(1) Network Database ",
            "(2) Hierarchical Database",
            "(3) Relational Database",
            "(4) Multiple Database",
            "(5) None of these",
            "7. The database stores information in <font color=#0099ff>(SBI PO 2010)</font>",
            "(1) rows and columns ",
            "(2) blocks",
            "(3) tracks and sectors ",
            "(4) All of these",
            "(5) None of these",
            "8. To locate a data item for storage is <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) field ",
            "(2) feed",
            "(3) database ",
            "(4) fetch",
            "(5) None of these",
            "9. Devices that could be used to input data into a database are",
            "(1) keyboard, fax roller ball",
            "(2) mouse, keyboard, monitor",
            "(3) mouse, keyboard, touch screen",
            "(4) All of the above",
            "(5) None of these",
            "10. In a relational database, a data structure that organises the information about a single topic into rows and columns, is <font color=#0099ff>(RBI PO 2011)</font>",
            "(1) block ",
            "(2) record ",
            "(3) tuple ",
            "(4) table",
            "(5) None of these",
            "11. The smallest unit of information about a record in a database is called a",
            "(1) cell ",
            "(2) field",
            "(3) record ",
            "(4) query",
            "(5) None of these",
            "12. ……… are distinct items that don’t have much meaning to you in a given context. <font color=#0099ff>(SBI PO 2012)</font>",
            "(1) Fields ",
            "(2) Data",
            "(3) Queries ",
            "(4) Properties",
            "(5) None of these",
            "13. The cardinality property of a relation, refers to the",
            "(1) number of database ",
            "(2) number of columns",
            "(3) number of rows ",
            "(4) number of tables",
            "(5) None of these",
            "14. Rows of a relation are called",
            "(1) relation ",
            "(2) tuples",
            "(3) data structure ",
            "(4) an entity",
            "(5) None of these",
            "15. A collection of related files is called a <font color=#0099ff>(SBI PO 2011, IBPS Clerk 2013)</font>",
            "(1) character ",
            "(2) field",
            "(3) database ",
            "(4) record",
            "(5) None of these",
            "16. In the relational modes, cardinality is termed as <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) number of tuples ",
            "(2) number of attributes",
            "(3) number of tables ",
            "(4) number of constraints",
            "(5) None of the above",
            "17. Which of the following contains information about a single ‘entity’ in the database like a person, place, event or thing?",
            "(1) Query ",
            "(2) Form",
            "(3) Record ",
            "(4) Table",
            "(5) None of these",
            "18. DBMS is comprised of tables that made up of rows called ......... and columns called ......... .",
            "(1) fields, records ",
            "(2) records, fields",
            "(3) address, fields ",
            "(4) ranges, sheet",
            "(5) records, ranges",
            "19. What is a stored question about information in a database? <font color=#0099ff>(SBI Clerk 2015)</font>",
            "(1) Query ",
            "(2) Sort ",
            "(3) Report ",
            "(4) Record",
            "(5) Field",
            "20. A program that generally has more user-friendly interface than a DBMS is",
            "(1) front end ",
            "(2) repository",
            "(3) back end ",
            "(4) form",
            "(5) None of these"
    };
    String[] answersSet1 = {
            "(4)","(3)","(3)","(1)","(2)","(2)","(1)","(4)","(3)","(4)","(2)","(1)","(3)","(2)","(4)","(1)","(3)","(2)","(1)","(4)"

    };
    String[] questionsSet2 = {
            "1. Which of the following objects is/are contained in database?",
            "(1) Table ",
            "(2) Query",
            "(3) Form ",
            "(4) All of these",
            "(5) None of these",
            "2. Which of the following places the common data elements in order from smallest to largest?",
            "(1) Character, File, Record, Field, Database",
            "(2) Character, Record, Field, File, Database",
            "(3) Character, Field, Record, File, Database",
            "(4) Bit, Byte, Character, Record, Field, File, Database",
            "(5) None of these",
            "3. What is the overall term for creating, editing, formatting, storing, retrieving a text document? <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) Word processing ",
            "(2) Spreadsheet design",
            "(3) Web design ",
            "(4) Database management",
            "(5) Presentation generation",
            "4. The database administrator’s function in an organisation is <font color=#0099ff>(SBI PO 2010)</font>",
            "(1) to be responsible for the technical aspects of managing the information contained in organisational databases",
            "(2) to be responsible for the executive level aspects of decision regarding the information management",
            "(3) to show the relationship among entity classes in a data warehouse",
            "(4) to define which data mining tools must be used to extract data",
            "(5) None of the above",
            "5. The code that relational database management systems use to perform their database task is referred to as",
            "(1) QBE ",
            "(2) SQL",
            "(3) OLAP ",
            "(4) Sequel Server",
            "(5) None of these",
            "6. DBMS helps to achieve",
            "(1) data independence",
            "(2) centralised control of data",
            "(3) selection of data ",
            "(4) Both ‘1’ and ‘2’",
            "(5) None of these",
            "7. Which out of the following is not a DBMS software?",
            "(1) dBASE ",
            "(2) FoxPro ",
            "(3) Oracle ",
            "(4) SyBase",
            "(5) Database 2000",
            "8. In which, the database can be restored up to the last consistent state after the system failure?",
            "(1) Backup ",
            "(2) Recovery",
            "(3) Redundancy ",
            "(4) Security",
            "(5) None of these",
            "9. ............ provides total solutions to reduce data redundancy, inconsistency, dependence and unauthorised access of data. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) DBMS ",
            "(2) Tables",
            "(3) Database ",
            "(4) Protection password",
            "(5) Centralisation of data",
            "10. Periodically adding, changing and deleting file records is called ......... file.",
            "(1) updating ",
            "(2) upgrading",
            "(3) restructuring ",
            "(4) renewing",
            "(5) None of these",
            "11. Architecture of database management can be viewed as",
            "(1) two levels ",
            "(2) four levels",
            "(3) three levels ",
            "(4) one level",
            "(5) None of these",
            "12. A collection of conceptual tools for describing data, relationships, semantics and constraints is referred to as <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) E-R model ",
            "(2) database",
            "(3) data model ",
            "(4) DBMS",
            "(5) None of these",
            "13. ......... is one reason for problems of data integrity. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) Data availability constraints",
            "(2) Data inconsistency",
            "(3) Security constraints",
            "(4) Unauthorised access of data",
            "(5) Data redundancy",
            "14. ......... means that the data contained in a database is accurate and reliable.",
            "(1) Data redundancy",
            "(2) Data integrity",
            "(3) Data reliability",
            "(4) Data consistency",
            "(5) None of the above",
            "15. Which of the following contains data descriptions and defines the name, data type and length of each field in the database?",
            "(1) Data dictionary ",
            "(2) Data table",
            "(3) Data record ",
            "(4) Data filed",
            "(5) None of these",
            "16. An advantage of the database management approach is",
            "(1) data is dependent on programs",
            "(2) data redundancy increases",
            "(3) data is integrated and can be accessed by multiple programs",
            "(4) All of the above",
            "(5) None of these",
            "17. Which of the following is the drawback of DBMS?",
            "(1) Improvement in Data",
            "(2) Backup and recovery",
            "(3) Complexity",
            "(4) Maintenance of Data Integrity",
            "(5) None of these",
            "18. In which of the following, database are used?",
            "(1) Banking ",
            "(2) Finance",
            "(3) Sales ",
            "(4) All of these",
            "(5) None of these",
            "19. A database that contains tables linked by common fields is called a",
            "(1) centralised database ",
            "(2) flat file database",
            "(3) relational database ",
            "(4) All of these",
            "(5) None of these",
            "20. Oracle is a (n) <font color=#0099ff>(IBPS Clerk 2014, IBPS Clerk Mains 2017)</font>",
            "(1) hardware ",
            "(2) high level language",
            "(3) operating system ",
            "(4) system software",
            "(5) RDBMS"
    };
    String[] answersSet2 = {
            "(4)","(3)","(4)","(1)","(2)","(4)","(5)","(2)","(4)","(1)","(3)","(3)","(1)","(2)","(1)","(3)","(3)","(4)","(3)","(5)"

    };
    String[] questionsSet3 = {
            "1. A set of possible data values is called",
            "(1) attribute ",
            "(2) degree ",
            "(3) tuple ",
            "(4) domain",
            "(5) None of these",
            "2. The purpose of the primary key in a database is to <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) unlock the database",
            "(2) provide a map of the data",
            "(3) uniquely identify a record",
            "(4) establish constraints on database operations",
            "(5) None of these",
            "3. In case of entity integrity, the primary key may be",
            "(1) not null ",
            "(2) null",
            "(3) Both ‘1’ and ‘2’ ",
            "(4) any value",
            "(5) None of these",
            "4. In files, there is a key associated with each record which is used to differentiate among different records. For every file, there is atleast one set of keysthat isunique. Such a key is called",
            "(1) unique key ",
            "(2) prime attribute",
            "(3) index key ",
            "(4) primary key",
            "(5) None of these",
            "5. Which of the following types of table constraints will prevent the entry of duplicate rows?",
            "(1) Primary key ",
            "(2) Unique",
            "(3) Null ",
            "(4) Foreign key",
            "(5) None of these",
            "6. The particular field of a record that uniquely identifies each record is called the <font color=#0099ff>(SBI PO 2012)</font>",
            "(1) key field ",
            "(2) primary field",
            "(3) master field ",
            "(4) order field",
            "(5) None of these",
            "7. ......... is a primary key of one file that also appears in another file. <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) Physical key ",
            "(2) Primary key",
            "(3) Foreign key ",
            "(4) Logical key",
            "(5) None of the above",
            "8. ......... is an invalid type of database key. ",
            "(1) Structured primary key <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(2) Atomic primary key",
            "(3) Primary key",
            "(4) Composite primary key",
            "(5) None of the above",
            "9. Key to represent relationship between tables is called <font color=#0099ff>(SBI Clerk 2010)</font>",
            "(1) primary key ",
            "(2) secondary key",
            "(3) foreign key ",
            "(4) composite key",
            "(5) None of the above",
            "10. Dr. E F Codd represented ......... rules that a database must obey if it has to be considered truly relational. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) 10 ",
            "(2) 8 ",
            "(3) 12 ",
            "(4) 6",
            "(5) 5",
            "11. A logical schema <font color=#0099ff>(SBI PO 2011)</font>",
            "(1) is the entire database",
            "(2) is a standard way of organising information into accessable part",
            "(3) describes how data is actually stored on disk",
            "(4) All of the above",
            "(5) None of the above",
            "12. Data duplication wastes the space, but also promotes a more serious problem called",
            "(1) isolated ",
            "(2) data inconsistency",
            "(3) other than those given as options",
            "(4) program dependency",
            "(5) separated data",
            "13. When data changes in multiple lists and all lists are not updated. This causes <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) Data redundancy ",
            "(2) Information overload",
            "(3) Duplicate data ",
            "(4) Data consistency",
            "(5) Data inconsistency",
            "14. Which database language is used to access data in existing database?",
            "(1) DDL ",
            "(2) DML",
            "(3) DCL ",
            "(4) None of these",
            "(5) All ",
            "15. An E-R diagram is a graphic method of presenting <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) primary keys and their relationships",
            "(2) primary keys and their relationships to instances",
            "(3) entity classes and their relationships",
            "(4) entity classes and their relationships to primary keys",
            "(5) None of the above",
            "16. In an E-R diagram, an entity set is are represented by",
            "(1) rectangle ",
            "(2) square ",
            "(3) ellipse ",
            "(4) triangle",
            "(5) circle",
            "17. In an E-R diagram, attributes are represented by",
            "(1) rectangle ",
            "(2) square",
            "(3) ellipse ",
            "(4) circle",
            "(5) None of these",
            "18. In E-R diagram, relationship type is represented by <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) ellipse ",
            "(2) dashed ellipse",
            "(3) rectangle ",
            "(4) diamond",
            "(5) None of these",
            "19. An entity set that does not have sufficient attributes to form a primary key, is a <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) strong entity set ",
            "(2) weak entity set",
            "(3) simple entity set ",
            "(4) primary entity set",
            "(5) None of these",
            "20. Relationship can be divided into",
            "(1) One to one ",
            "(2) Many to one",
            "(3) One to many ",
            "(4) All of these",
            "(5) None of these"
    };
    String[] answersSet3 = {
            "(4)","(3)","(1)","(4)","(1)","(2)","(3)","(1)","(3)","(3)","(2)","(2)","(5)","(2)","(3)","(1)","(3)","(4)","(2)","(4)"

    };
    String[] questionsSet4 = {

    };
    String[] answersSet4 = {

    };

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }

    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }
}



