package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter4 {

    String[] questionsSet1 = {
            "1. Which is representative of the size of the memory?",
            "(1) Storage capacity",
            "(2) Access mode",
            "(3) Access time",
            "(4) Permanence storage",
            "(5) None of the above",
            "2. Where is data saved permanently?",
            "(1) Memory ",
            "(2) Storage",
            "(3) CPU ",
            "(4) Printer",
            "(5) None of the above",
            "3. Where are programs and data to be used by the computer available? <font color=#0099ff>(SSC FCI 2012)</font>",
            "(1) Processing unit ",
            "(2) Output",
            "(3) Storage ",
            "(4) Input",
            "(5) None of the above",
            "4. How many types of memory does a computer have?",
            "(1) Four ",
            "(2) Eight",
            "(3) One ",
            "(4) Two",
            "(5) None of the above",
            "5. Primary storage is .......... as compared to secondary storage.",
            "(1) slow and inexpensive",
            "(2) fast and inexpensive",
            "(3) fast and expensive",
            "(4) slow and expensive",
            "(5) None of the above",
            "6. The key feature(s) of internal memory is/are",
            "(1) limited storage capacity",
            "(2) temporary storage",
            "(3) fast access and high cost",
            "(4) All of the above",
            "(5) None of the above",
            "7. Internal storage is also called main",
            "(1) memory ",
            "(2) area",
            "(3) screen ",
            "(4) unit",
            "(5) None of the above",
            "8. The two kinds of main memory are",
            "(1) ROM and RAM",
            "(2) primary and secondary",
            "(3) floppy disk and hard disk",
            "(4) direct and sequential",
            "(5) None of the above",
            "9. Which memory is used as temporary memory?",
            "(1) Non-volatile memory",
            "(2) Volatile memory",
            "(3) Hard disk memory",
            "(4) Read only memory",
            "(5) None of the above",
            "10. Which of the following is a correct definition of volatile memory?",
            "(1) It does retain its contents at high temperatures",
            "(2) It is to be kept in air-tight boxes",
            "(3) It loses its contents on failure of power supply",
            "(4) It does not lose its contents on failure of power supply",
            "(5) None of the above",
            "11. Cache and main memory will not be able to hold their contents when the power is OFF. They are <font color=#0099ff>(Allahabad Bank PO 2012)</font>",
            "(1) dynamic ",
            "(2) static",
            "(3) volatile ",
            "(4) non-volatile",
            "(5) faulty",
            "12. Which of the following is not an access mode?",
            "(1) Random ",
            "(2) Sequential",
            "(3) Continuous ",
            "(4) Direct",
            "(5) None of the above",
            "13. ……memory in a computer is where information is temporarily stored while it is being accessed or worked on by the processor. <font color=#0099ff>(IBPS RRB PO 2017)</font>",
            "(1) Logical ",
            "(2) Secondary",
            "(3) ROM ",
            "(4) RAM",
            "(5) Cache",
            "14. Why RAM is so called? <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) Because it is read and write memory",
            "(2) Because it is a volatile memory",
            "(3) Because it can be selected directly for storing and retrieving data and instructions of any location of chip",
            "(4) Because it is a non-volatile memory",
            "(5) None of the above",
            "15. Which of the following is not true about RAM? <font color=#0099ff>(IBPS PO 2015, IBPS Clerk 2014)</font>",
            "(1) RAM is the same as hard disk storage",
            "(2) RAM is a temporary storage area",
            "(3) RAM is volatile",
            "(4) RAM is a primary memory",
            "(5) Other than those given as options",
            "16. Virtual memory allocates hard disk space to supplement the immediate, functional memory capacity of <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) ROM ",
            "(2) EPROM",
            "(3) The registers ",
            "(4) Extended memory",
            "(5) RAM",
            "17. Information stored in RAM need to be <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) check ",
            "(2) refresh periodically",
            "(3) modify ",
            "(4) detecting errors",
            "(5) None of these",
            "18. Storage that retains its data after the power is turned OFF is referred to as <font color=#0099ff>(SBI Clerk 2009)</font>",
            "(1) volatile storage ",
            "(2) non-volatile storage",
            "(3) sequential storage ",
            "(4) direct storage",
            "(5) None of these",
            "19. Dynamic RAM consumes …… power and …… than static RAM.",
            "(1) more, faster ",
            "(2) more, slower",
            "(3) less, slower ",
            "(4) less, faster",
            "(5) None of the above",
            "20. Which of the following memory chip is faster? <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) There is no certainty ",
            "(2) DRAM",
            "(3) SRAM ",
            "(4) RAM",
            "(5) None of these",
    };
    String[] answersSet1 = {"(1)", "(2)", "(3)", "(4)", "(3)", "(4)", "(1)", "(1)", "(2)", "(3)", "(3)", "(1)", "(4)", "(3)", "(1)", "(5)", "(2)", "(2)", "(3)", "(3)"
    };

    String[] questionsSet2 = {
            "1. The advantage of DRAM is",
            "(1) it is cheaper than SRAM",
            "(2) it can store more than that of SRAM",
            "(3) it is faster than SRAM",
            "(4) data can be erased easily in it as compared to SRAM",
            "(5) None of the above",
            "2. What is called the permanent memory built into your computer?",
            "(1) RAM ",
            "(2) ROM",
            "(3) CPU ",
            "(4) CD-ROM",
            "(5) None of the above",
            "3. Permanent instructions that the computer use when it is turned ON and that cannot be changed by other instructions are contained in",
            "(1) ROM ",
            "(2) RAM",
            "(3) ALU ",
            "(4) SRAM",
            "(5) None of the above",
            "4. Which of the following is not a ROM?",
            "(1) PROM ",
            "(2) EPROM",
            "(3) EEPROM ",
            "(4) EDPROM",
            "(5) None of the above",
            "5. When you first turn on a computer, the CPU is preset to execute instructions stored in the <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) RAM ",
            "(2) flash memory",
            "(3) ROM ",
            "(4) CD-ROM",
            "(5) ALU",
            "6. A disc’s content that is recorded at the time of manufacture and that cannot be changed or erased by the user is <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) memory only ",
            "(2) write only",
            "(3) once only ",
            "(4) run only",
            "(5) read only",
            "7. An area of computer that temporarily holds data waiting to be processed is",
            "(1) CPU ",
            "(2) memory",
            "(3) storage ",
            "(4) file",
            "(5) None of the above",
            "8. The difference between memory and storage is that memory is …… and storage is ……… . <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) temporary; permanent",
            "(2) permanent; temporary",
            "(3) slow; fast",
            "(4) non-volatile; volatile",
            "(5) None of the above",
            "9. Cache memory acts between",
            "(1) CPU and RAM",
            "(2) RAM and ROM",
            "(3) CPU and hard disk",
            "(4) All of these",
            "(5) None of the above",
            "10. The most frequently used instructions of a computer program are likely to be fetched from",
            "(1) the hard disk ",
            "(2) cache memory",
            "(3) RAM ",
            "(4) registers",
            "(5) None of the above",
            "11. Which of the following is the high speed memory which compensates the gap in speeds of processor and main memory? <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) Cache ",
            "(2) PROM",
            "(3) EPROM ",
            "(4) SRAM",
            "(5) None of these",
            "12. ......... acts as temporary high speed holding area between the memory and the CPU thereby improving processing capabilities. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) ROM ",
            "(2) RAM",
            "(3) Temporary memory ",
            "(4) Cache memory",
            "(5) Flash memory",
            "13. Which of the following statements is/are true? <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) Cache memories are bigger than RAM",
            "(2) Cache memories are smaller than RAM",
            "(3) ROM are faster than RAM",
            "(4) Information in ROM can be written by users",
            "(5) None of the above",
            "14. ......... is having more memory addresses than are physically available. <font color=#0099ff>(SBI PO 2014)</font>",
            "(1) Virtual memory ",
            "(2) System software",
            "(3) Application software ",
            "(4) RAM",
            "(5) Vertical memory",
            "15. Virtual memory is <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) an extremely large main memory",
            "(2) an extremely large secondary memory",
            "(3) an illusion of extremely large main memory",
            "(4) a type of memory used in super computers",
            "(5) None of the above",
            "16. ……… is the ability of a device to ‘jump’ directly to the requested data. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) Sequential access ",
            "(2) Random access",
            "(3) Quick access",
            "(4) All of the above",
            "(5) None of the above",
            "17. The ……… is the amount of data that a storage device can move from the storage to the computer per second. <font color=#0099ff>(IBPS Clerk 2012)</font>",
            "(1) data migration rate",
            "(2) data digitising rate",
            "(3) data transfer rate",
            "(4) data access rate",
            "(5) None of the above",
            "18. The main directory of a disk is called the ……… directory. <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) Network",
            "(2) Folder",
            "(3) Root",
            "(4) Other than those given as options",
            "(5) Program",
            "19. The …… indicates how much data a particular storage medium can hold. <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) storage ",
            "(2) access",
            "(3) capacity ",
            "(4) memory",
            "(5) None of these",
            "20. What is the main folder on a storage device? <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) Root directory ",
            "(2) Interface",
            "(3) Device driver ",
            "(4) Platform",
            "(5) Main directory"
    };
    String[] answersSet2 = {"(1)", "(2)", "(1)", "(4)", "(3)", "(5)", "(2)", "(1)", "(1)", "(2)", "(1)", "(4)", "(2)", "(1)", "(3)", "(2)", "(2)", "(3)", "(3)", "(1)"
    };

    String[] questionsSet3 = {
            "1. Which of the following computer’s memory is characterised by low cost per bit stored?",
            "(1) primary ",
            "(2) secondary",
            "(3) hard disk ",
            "(4) All of these",
            "(5) None of the above",
            "2. Secondary storage",
            "(1) does not require constant power",
            "(2) does not magnetic media",
            "(3) consists of four main types of devices",
            "(4) does not store information for later retrieval",
            "(5) None of the above",
            "3. Which of the following is not used as secondary storage?",
            "(1) Semi-conductor memory",
            "(2) Magnetic disks",
            "(3) Magnetic drums",
            "(4) Magnetic tapes",
            "(5) None of the above",
            "4. The secondary storage devices can only store data but they cannot perform",
            "(1) arithmetic operations",
            "(2) logic operations",
            "(3) fetch operations",
            "(4) All of the above",
            "(5) None of the above",
            "5. Where do you save the data that, your data will remain intact even when the computer is turned OFF?",
            "(1) RAM",
            "(2) Motherboard",
            "(3) Secondary storage device",
            "(4) Primary storage device",
            "(5) None of the above",
            "6. The term ……… refers to data storage systems that make it possible for a computer or electronic device to store and retrieve data. <font color=#0099ff>(SBI PO 2010)</font>",
            "(1) retrieval technology",
            "(2) input technology",
            "(3) output technology ",
            "(4) storage technology",
            "(5) None of these",
            "7. The storage device used to compensate for the difference in rates of flow of data from one device to another is termed as <font color=#0099ff>(SBI PO 2011)</font>",
            "(1) chip ",
            "(2) channel",
            "(3) floppy ",
            "(4) call",
            "(5) buffer",
            "8. Which of the following is the magnetic storage device?",
            "(1) Hard disk ",
            "(2) Compact disc",
            "(3) Audio tapes ",
            "(4) All of these",
            "(5) None of the above",
            "9. The concentric circles on the floppy disk are further divided into",
            "(1) tracks ",
            "(2) sectors",
            "(3) cylinders ",
            "(4) circles",
            "(5) None of the above",
            "10. A track location that cuts across all platters is called a",
            "(1) cylinder ",
            "(2) spindle",
            "(3) diskette ",
            "(4) platters",
            "(5) None of the above",
            "11. The primary device that a computer uses to store information is <font color=#0099ff>(Punjab & Sind Bank Clerk 2010)</font>",
            "(1) TV ",
            "(2) storehouse",
            "(3) desk ",
            "(4) hard drive",
            "(5) None of these",
            "12. Hard disk devices are considered …… storage. <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) flash ",
            "(2) temporary",
            "(3) worthless ",
            "(4) non-volatile",
            "(5) non-permanent",
            "13. The thick, rigid metal plotters that are capable of retrieving information at a high rate of speed are known as <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) hard disks ",
            "(2) SAN",
            "(3) soft disks ",
            "(4) flash memory",
            "(5) None of the above",
            "14. Hard drive is used to store <font color=#0099ff>(IBPS Clerk Mains 2017)</font>",
            "(1) volatile data",
            "(2) non-volatile data",
            "(3) permanent data",
            "(4) temporary data",
            "(5) intermediate data",
            "15. The hard drive is normally located",
            "(1) next to the printer ",
            "(2) plugged into the back of the computer",
            "(3) underneath the monitor",
            "(4) on top of the CD-ROM",
            "(5) inside the system base unit",
            "16. Data on a floppy disk is recorded in rings called",
            "(1) sectors ",
            "(2) ringers",
            "(3) rounders ",
            "(4) tracks",
            "(5) None of the above",
            "17. Which of the following is/are example(s) of magnetic storage media?",
            "(1) Zip disk ",
            "(2) CD-ROM",
            "(3) Floppy disk ",
            "(4) DVD",
            "(5) Both ‘1’ and ‘3’",
            "18. Floppy disks are organised as <font color=#0099ff>(IBPS PO 2012)</font>",
            "(1) files ",
            "(2) heads and folders",
            "(3) tracks and sectors ",
            "(4) All of these",
            "(5) None of the above",
            "19. The capacity of 3.5 inch floppy disk is <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) 1.40 MB ",
            "(2) 1.44 GB",
            "(3) 1.40 GB ",
            "(4) 1.45 MB",
            "(5) 1.44 MB",
            "20. The most common storage device for the personal computer is the <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) floppy disk",
            "(2) USB personal computer",
            "(3) mainframe",
            "(4) a laptop",
            "(5) None of the above"
    };
    String[] answersSet3 = {"(2)", "(1)", "(1)", "(4)", "(3)", "(4)", "(5)", "(1)", "(2)", "(1)", "(4)", "(4)", "(1)", "(3)", "(5)", "(4)", "(5)", "(3)", "(5)", "(1)"
    };
    String[] questionsSet4 = {
            "1. Which of the following has the smallest storage capacity? <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) Zip disk ",
            "(2) Hard disk",
            "(3) Floppy disk ",
            "(4) Data cartridge",
            "(5) CD",
            "2. ‘FDD’ stands for <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) Floppy Drive Detector",
            "(2) Floppy Drive Demodulator",
            "(3) Floppy Disk Drive",
            "(4) Floppy Demodulator Disc",
            "(5) None of the above",
            "3. ......... is the process of dividing the disc into tracks and sectors. <font color=#0099ff>(SBI PO 2015, IBPS Clerk Mains 2017)</font>",
            "(1) Tracking ",
            "(2) Formatting",
            "(3) Crashing ",
            "(4) Allotting",
            "(5) None of these",
            "4. Data on a floppy disk was recorded in rings called <font color=#0099ff>(IBPS RRB PO 2017)</font>",
            "(1) flip ",
            "(2) ringers ",
            "(3) rounders",
            "(4) fields ",
            "(5) segments",
            "5. Tape drive provides …… access to data.",
            "(1) timely ",
            "(2) sporadic",
            "(3) random ",
            "(4) sequential",
            "(5) None of the above",
            "6. Magnetic tape is not practical for applications where data must be quickly recalled because tape is",
            "(1) a random access medium",
            "(2) a sequential access medium",
            "(3) a read only medium",
            "(4) fragile and easily damaged",
            "(5) an expensive storage medium",
            "7. Which of the following storage media provides sequential access only?",
            "(1) Floppy disk ",
            "(2) Magnetic disk",
            "(3) Magnetic tape ",
            "(4) Optical disc",
            "(5) None of these",
            "8. Which of the following can hold maximum data?",
            "(1) Optical disc ",
            "(2) Floppy disk",
            "(3) Magnetic disk ",
            "(4) Magnetic tape",
            "(5) None of the above",
            "9. Which storage device is mounted on ‘reels’?",
            "(1) Floppy disk ",
            "(2) Hard disk",
            "(3) Magnetic tapes ",
            "(4) CD-ROM",
            "(5) None of the above",
            "10. Which of the following storage devices can be used for storing large backup data?",
            "(1) Floppy disk ",
            "(2) Hard disk",
            "(3) Magnetic tape ",
            "(4) All of these",
            "(5) None of the above",
            "11. On a CD-RW, you can",
            "(1) read and write information",
            "(2) only read information",
            "(3) only write information",
            "(4) read, write and rewrite information",
            "(5) None of the above",
            "12. Which of the following are advantages of CD-ROM as a storage media? <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) CD-ROM is an inexpensive way to store large amount of data and information",
            "(2) CD-ROM discs retrieve data and information more quickly than magnetic disks",
            "(3) CD-ROMs make less errors than magnetic media Computer Memory 41",
            "(4) All of the above",
            "(5) None of the above",
            "13. Which media has the ability to have data/information stored (written) on them by users more than once? <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) CD-R discs ",
            "(2) CD-RW discs",
            "(3) Zip discs ",
            "(4) Optical discs",
            "(5) CD-RW discs and Zip discs",
            "14. What is the difference between a CD-ROM and CD-RW? <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) They are the same—just two different terms used by different manufactures.",
            "(2) A CD-ROM can be written to and a CD-RW cannot.",
            "(3) Other than those given as options",
            "(4) A CD-ROM holds more information than a CD-RW.",
            "(5) A CD-RW can be written to but a CD-ROM can only be read from.",
            "15. Compact disc that can store approximately 650-800 MB of data or 74-80 min of music are <font color=#0099ff>(SBI Clerk 2015)</font>",
            "(1) zip discs ",
            "(2) CD-ROM",
            "(3) video cards ",
            "(4) pressing machines",
            "(5) floppy diskettes",
            "16. The CD-ROM drive is used to <font color=#0099ff>(Allahabad Bank PO 2011)</font>",
            "(1) play compact discs ",
            "(2) play music",
            "(3) install software ",
            "(4) control digital information",
            "(5) None of the above",
            "17. A flat metallic disk that contains a large amount of permanently stored information read optically, is called a",
            "(1) monitor ",
            "(2) ALU",
            "(3) CD-ROM ",
            "(4) RAM",
            "(5) None of these",
            "18. CD-ROM is an example of <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) input device",
            "(2) output device",
            "(3) Both input & output",
            "(4) Memory device",
            "(5) None of the above",
            "19. Which of the following has the largest storage capacity for removable media?",
            "(1) Floppy disk ",
            "(2) CD-ROM",
            "(3) DVD ",
            "(4) Partitioned space",
            "(5) None of the above",
            "20. Which of the following is an example of optical disc? <font color=#0099ff>(Allahabad Bank PO 2011)</font>",
            "(1) Digital versatile discs ",
            "(2) Magnetic disks",
            "(3) Memory disks ",
            "(4) Data bus disks",
            "(5) None of the above"
    };
    String[] answersSet4 = {"(3)", "(3)", "(2)", "(5)", "(4)", "(2)", "(4)", "(4)", "(3)", "(1)", "(4)", "(1)", "(2)", "(5)", "(2)", "(1)", "(3)", "(4)", "(3)", "(1)"
    };

    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }
}



