package com.srinivasinfotech.computertests.QuestionsLibrary;

public class Chapter9 {


    String[] questionsSet1 = {
            "1. Microsoft Office was developed by ………… in …",
            "(1) Microsoft Inc, 1970s",
            "(2) Microsoft Inc, 1980s",
            "(3) Sun Microsoft, 1980s",
            "(4) Sun Microsoft Inc, 1970s",
            "(5) None of the above",
            "2. Which of the following is a basic software of MS-Office?",
            "(1) MS-Word ",
            "(2) MS-Excel",
            "(3) MS-PowerPoint ",
            "(4) MS-Access",
            "(5) All of the above",
            "3. MS-Word is a",
            "(1) tabular data formatting software",
            "(2) Word processing software",
            "(3) presentation software",
            "(4) E-mail client",
            "(5) None of the above",
            "4. What is MS-Word? <font color=#0099ff>(SBI Clerk 2015)</font>",
            "(1) It is a calculating tool.",
            "(2) It is a planning tool.",
            "(3) It is a chart.",
            "(4) It is a networking tool.",
            "(5) It is a document typing tool.",
            "5. Microsoft Office Word is a(n)",
            "(1) area in the computer’s main memory in which Microsoft Office text files are stored temporarily",
            "(2) programincludedwithWindows2000thatcan beusedonlytocreateoredittextfiles,smaller than64k,thatdonotrequireformatting",
            "(3) classified password that prevents unauthorised users from accessing a protected Microsoft Office item or document",
            "(4) full featured Word processing program that can be used to create and revise professional looking documents easily",
            "(5) None of the above",
            "6. A program which helps to create written documents and lets you go back and make corrections as necessary.",
            "(1) Spreadsheet ",
            "(2) Personal writer",
            "(3) Word printer ",
            "(4) Word processor",
            "(5) None of the above",
            "7. A Word processor would be used best to",
            "(1) paint a picture ",
            "(2) draw a diagram",
            "(3) type a story",
            "(4) work out income and expenses",
            "(5) None of the above",
            "8. This program is made by Microsoft and embedded with Windows and used to view Web document. <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) Netscape ",
            "(2) Outlook Express",
            "(3) Internet Explorer ",
            "(4) MS-Word",
            "(5) None of these",
            "9. You can start Microsoft Word by using which button?",
            "(1) New ",
            "(2) Start",
            "(3) Program ",
            "(4) All of these",
            "(5) None of the above",
            "10. When you start MS-Word, the opening document has the name as",
            "(1) DOC 1 ",
            "(2) Document1",
            "(3) Document ",
            "(4) Workbook",
            "(5) None of the above",
            "11. What is the default file extension for all Word documents? <font color=#0099ff>(RBI Grade B 2012, IBPS Clerk 2014)</font>",
            "(1) WRD ",
            "(2) TXT",
            "(3) DOC ",
            "(4) FIL",
            "(5) WD",
            "12. The first bar of MS-Word is",
            "(1) menu bar ",
            "(2) status bar",
            "(3) title bar ",
            "(4) formatting toolbar",
            "(5) None of the above",
            "13. Editing a document that has been created means <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) saving it ",
            "(2) printing it",
            "(3) scanning it ",
            "(4) correcting it",
            "(5) None of these",
            "14. A ...... is an additional set of commands that the computer displays after you make a selection from main menu. <font color=#0099ff>(SBI Clerk 2009)</font>",
            "(1) dialog box ",
            "(2) sub menu",
            "(3) menu selection ",
            "(4) All of these",
            "(5) None of these",
            "15. Microsoft Word is a word processor developed by Microsoft. In MS-Word, Spelling Check is a feature available in which tab?",
            "(1) File ",
            "(2) Home",
            "(3) Insert ",
            "(4) Review",
            "(5) References",
            "16. MS-Word is a text or document editing application program that comes in the package of MS-Office Suite. Which among the given options is not related with MS-Word? <font color=#0099ff>(IBPS PO 2016)</font>",
            "(1) Page Layout ",
            "(2) Antivirus",
            "(3) Mailings ",
            "(4) Format Painter",
            "(5) SmartArt",
            "17. In order to choose the font for a sentence in a Word document <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) select Font in the Format menu",
            "(2) select Font in the Edit menu",
            "(3) select Font in the Tools menu",
            "(4) select Font in the View menu",
            "(5) None of the above",
            "18. When computer users …… a document, they change its appearance.",
            "(1) Edit ",
            "(2) Create ",
            "(3) Save ",
            "(4) Format",
            "(5) None of these",
            "19. In Word, the Replace option is available on",
            "(1) File menu ",
            "(2) Edit menu",
            "(3) Insert menu ",
            "(4) View menu",
            "(5) Format menu",
            "20. Which of the following is not an option of Edit menu?",
            "(1) Cut ",
            "(2) Copy",
            "(3) Paste ",
            "(4) Page Setup",
            "(5) None of these",
    };
    String[] answersSet1 = {
            "(2)","(5)","(2)","(5)","(2)","(4)","(3)","(4)","(2)","(2)","(3)","(3)","(4)","(2)","(4)","(2)","(1)","(1)","(2)","(4)"

    };
    String[] questionsSet2 = {
            "1. MS-Excel is used for <font color=#0099ff>(SBI Clerk 2012)</font>",
            "(1) letter writing",
            "(2) spreadsheet calculation",
            "(3) presentation",
            "(4) painting",
            "(5) None of the above",
            "2. What kind of software would you most likely use to keep track of a billing account? <font color=#0099ff>(IBPS PO 2015)</font>",
            "(1) Web Authoring ",
            "(2) Electronic Publishing",
            "(3) Spreadsheet ",
            "(4) Word Processing",
            "(5) PowerPoint",
            "3. Excel worksheet data can be shared with Word document by <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) inserting an Excel file into Word",
            "(2) copy and paste Excel worksheet into Word document",
            "(3) link Excel data in a Word document",
            "(4) All of the above",
            "(5) None of the above",
            "4. A worksheet is made of columns and rows, wherein <font color=#0099ff>(RBI Grade 2013)</font>",
            "(1) columns run horizontally and rows run vertically",
            "(2) columns run vertically and rows run horizontally",
            "(3) the run is dependent on the application being used",
            "(4) Both ‘2’ and ‘3’",
            "(5) None of the above",
            "5. Which of the following software applications would be the most appropriate for performing numerical and statistical calculations? <font color=#0099ff>(RBI Grade B 2012)</font>",
            "(1) Database",
            "(2) Document processor",
            "(3) Graphics package",
            "(4) Spreadsheet",
            "(5) PowerPoint",
            "6. The file responsible for starting MS-Excel is <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) MS.Excel ",
            "(2) MS.exe",
            "(3) Excel.exe ",
            "(4) Excel.com",
            "(5) None of these",
            "7. Anything that is typed in a worksheet appears <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) in the formula bar only",
            "(2) in the active cell only",
            "(3) in both active cell and formula bar",
            "(4) All of the above",
            "(5) None of the above",
            "8. Which one is the example of spreadsheet package? <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) VisiCalc ",
            "(2) Unity",
            "(3) Ada ",
            "(4) Snowball",
            "(5) None of these",
            "9. Which option will we use to give heading in the form ?",
            "(1) Label ",
            "(2) Text box",
            "(3) Option group ",
            "(4) Insert",
            "(5) None of these",
            "10. The extension of saved file in MS-Excel is",
            "(1) .xis ",
            "(2) .xas",
            "(3) .xlsx ",
            "(4) .xll",
            "(5) .lxs",
            "11. Alignment buttons are available on which toolbar?",
            "(1) Status ",
            "(2) Standard",
            "(3) Formatting ",
            "(4) All of these",
            "(5) None of these",
            "12. In Excel, the intersection of a column and a row is called <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) cell ",
            "(2) grid ",
            "(3) table ",
            "(4) box",
            "(5) None of these",
            "13. What does an electronic spreadsheet consist of? <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) Rows ",
            "(2) Columns",
            "(3) Cells ",
            "(4) All of these",
            "(5) None of these",
            "14. A collection of worksheets is called <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) Excel book ",
            "(2) Worksheets",
            "(3) Excel sheets ",
            "(4) Workbook",
            "(5) None of these",
            "15. All of the following terms are related to spreadsheet software except <font color=#0099ff>(SBI Clerk 2011)</font>",
            "(1) worksheet ",
            "(2) cell",
            "(3) formula ",
            "(4) virus detection",
            "(5) None of these",
            "16. Which of the following is an active cell in Excel? <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) Current cell ",
            "(2) Formula",
            "(3) Range ",
            "(4) Cell address",
            "(5) None of these",
            "17. How are the data organised in a spreadsheet? <font color=#0099ff>(SBI Clerk 2008)</font>",
            "(1) Lines and spaces ",
            "(2) Layers and planes",
            "(3) Height and width ",
            "(4) Rows and columns",
            "(5) None of these",
            "18. The basic unit of a worksheet into which you enter data in Excel is called a <font color=#0099ff>(IBPS Clerk 2008)</font>",
            "(1) tab ",
            "(2) cell ",
            "(3) box ",
            "(4) range",
            "(5) None of these",
            "19. The advantage of using a spreadsheet is",
            "(1) calculations can be done automatically",
            "(2) changing data automatically updates calculations",
            "(3) more flexibility",
            "(4) All of the above",
            "(5) None of the above",
            "20. A ......... is rectangular grid of rows and columns used to enter data.",
            "(1) cell ",
            "(2) workspace",
            "(3) worksheet ",
            "(4) spreadsheet",
            "(5) Both ‘3’ and ‘4",
    };
    String[] answersSet2 = {
            "(2)","(3)","(4)","(2)","(4)","(3)","(3)","(4)","(1)","(3)","(3)","(1)","(4)","(4)","(4)","(1)","(4)","(2)","(4)","(5)"

    };
    String[] questionsSet3 = {
            "1. Which software is used to create presentation?",
            "(1) Microsoft Word ",
            "(2) Microsoft Excel",
            "(3) Microsoft PowerPoint",
            "(4) Microsoft Access",
            "(5) All of the above",
            "2. What is the extension of PowerPoint in Microsoft Office 2007?",
            "(1) .ptp ",
            "(2) .pptx ",
            "(3) .ppx ",
            "(4) .ptx",
            "(5) .pt",
            "3. You can add any picture in your document from which menu?",
            "(1) File ",
            "(2) Edit ",
            "(3) Insert ",
            "(4) Format",
            "(5) View",
            "4. Which of the following should you use if you want all the slides in the presentation to have the same ‘look’?",
            "(1) The slide layout option",
            "(2) Add a slide option",
            "(3) Outline view",
            "(4) A presentation design template",
            "(5) None of the above",
            "5. The ......... defines the appearance and shape of letters, numbers and special characters.",
            "(1) font ",
            "(2) font size",
            "(3) point ",
            "(4) paragraph formatting",
            "(5) None of these",
            "6. ......... shows how the contents on printed page will appear with margin, header and footer.",
            "(1) Draft ",
            "(2) Full screen reading",
            "(3) Outline ",
            "(4) Page layout",
            "(5) None of these",
            "7. By default, on which page the header or footer is printed? <font color=#0099ff>(IBPS Clerk 2011)</font>",
            "(1) On first page ",
            "(2) On alternative page",
            "(3) On every page ",
            "(4) All of these",
            "(5) None of these",
            "8. To find the paste special option, or use the Clipboard group on the …… tab of Power Point. <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) Design ",
            "(2) Slide Show",
            "(3) Page Layout ",
            "(4) Insert",
            "(5) None of these",
            "9. This is to insert an object, which is not miss print to its originating document into a destination document? <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) Cell ",
            "(2) Embed",
            "(3) Defaults ",
            "(4) Any of these",
            "(5) None of these",
            "10. Selecting Portrait changes our page from <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) a wide to tall orientation",
            "(2) a tall to wide orientation",
            "(3) a normal font size to a condensed one",
            "(4) a condensed font size to a normal one",
            "(5) None of the above",
            "11. Which of the following controls the format and placement of the titles and text you on slides, as well as, background items and graphics you want to appear on every slide? <font color=#0099ff>(IBPS Clerk 2015)</font>",
            "(1) Slide ",
            "(2) Copyright",
            "(3) Layout ",
            "(4) Design",
            "(5) None of these",
            "12. Which of the following views is the best view to use when setting transition effects for all slides in presentation?",
            "(1) Slide sorter view ",
            "(2) Notes page view",
            "(3) Slide view ",
            "(4) Outline view",
            "(5) None of these",
            "13. Which PowerPoint view displays each slide of the presentation as a thumbnail and is useful for rearranging slides? <font color=#0099ff>(IBPS Clerk 2013)</font>",
            "(1) Slide sorter ",
            "(2) Slide show",
            "(3) Slide master ",
            "(4) Notes page",
            "(5) Slide design",
            "14. Which is a feature included in Microsoft PowerPoint software that allows the user to see all the slides in a presentation at one time? <font color=#0099ff>(IBPS PO 2016)</font>",
            "(1) Slide Sorter ",
            "(2) Slide Master",
            "(3) Handout Master ",
            "(4) Slide Header",
            "(5) Reading View",
            "15. To add a header or footer to your handout, you can use the",
            "(1) Title master ",
            "(2) Slide master",
            "(3) Handout master ",
            "(4) All of these",
            "(5) None of these",
            "16. The maximum zoom percentage in MS-PowerPoint is <font color=#0099ff>(IBPS Clerk 2009)</font>",
            "(1) 100% ",
            "(2) 200% ",
            "(3) 400% ",
            "(4) 500%",
            "(5) None of these",
            "17. In Microsoft PowerPoint, two kinds of sound effect files can be added to the presentation are",
            "(1) .wav files and .mid files",
            "(2) .wav files and .gif files",
            "(3) .wav files and .jpg files",
            "(4) .jpg files and .gif files",
            "(5) None of the above",
            "18. Which file format can be added to a PowerPoint show?",
            "(1) .jpg ",
            "(2) .giv ",
            "(3) .wav ",
            "(4) All of these",
            "(5) None of these",
            "19. PowerPoint provides .......... number of layouts for use with blank presentation.",
            "(1) 20 ",
            "(2) 22 ",
            "(3) 24 ",
            "(4) 26",
            "(5) None of these",
            "20. In PowerPoint, the Header and Footer buttons can be found on the Insert tab in which group? <font color=#0099ff>(IBPS PO 2012, Clerk 2013)</font>",
            "(1) Illustrations group ",
            "(2) Object group",
            "(3) Insert group ",
            "(4) Tables group",
            "(5) None of these",
    };
    String[] answersSet3 = {
            "(3)","(2)","(3)","(4)","(1)","(4)","(4)","(5)","(2)","(1)","(3)","(1)","(1)","(1)","(3)","(3)","(1)","(4)","(3)","(5)"

    };
    String[] questionsSet4 = {
            "1. Which command brings you to the first slide in your presentation?",
            "(1) Next slide button ",
            "(2) Page up",
            "(3) Ctrl + Home ",
            "(4) Ctrl + End",
            "(5) None of these",
            "2. Which of the following allows you to select more than one slides in a presentation?",
            "(1) Alt + click each slide",
            "(2) Shift + drag each slide",
            "(3) Shift + click each slide",
            "(4) Ctrl + click each slide",
            "(5) None of the above",
            "3. Which of the following will not advance the slides in a slide show view?",
            "(1) Esc key ",
            "(2) Spacebar",
            "(3) Enter key ",
            "(4) Mouse button",
            "(5) None of the above",
            "4. Which of the following bypasses the Print dialog box when printing individual slides or an entire presentation?",
            "(1) File, Print preview ",
            "(2) Print button",
            "(3) File, Print ",
            "(4) Ctrl + P",
            "(5) None of these",
            "5. Which key on the keyboard can be used to view slide show?",
            "(1) F1 ",
            "(2) F2",
            "(3) F5 ",
            "(4) F10",
            "(5) None of these",
            "6. In MS-Access, a table can have……primary key/keys.",
            "(1) One ",
            "(2) Two ",
            "(3) Three ",
            "(4) Four",
            "(5) None of these",
            "7. Which of the following is a DBMS software?",
            "(1) Access ",
            "(2) Excel",
            "(3) Word ",
            "(4) PowerPoint",
            "(5) None of these",
            "8. How many types of relationships are there in MS-Access?",
            "(1) 3 ",
            "(2) 4",
            "(3) 5 ",
            "(4) 6",
            "(5) None of these",
            "9. Attributes can be defined for",
            "(1) entity ",
            "(2) switch board",
            "(3) macro ",
            "(4) pages",
            "(5) None of these",
            "10. In order to include picture data type must be <font color=#0099ff>(RBI PO 2009)</font>",
            "(1) OLE ",
            "(2) hyperlink",
            "(3) Yes/No ",
            "(4) picture",
            "(5) None of these",
            "11. What is the default size of the data type in MS-Access ? <font color=#0099ff>(SBI Clerk 2010)</font>",
            "(1) 50 ",
            "(2) 60",
            "(3) 70 ",
            "(4) 80",
            "(5) None of these",
            "12. Which is the short key to invoke the spell checker in MS-Access? <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) F2 ",
            "(2) F7",
            "(3) Alt+F7 ",
            "(4) F3",
            "(5) None of these",
            "13. We can’t make query by Insert menu? <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) True ",
            "(2) False",
            "(3) Cannot say ",
            "(4) Sometimes",
            "(5) None of the above",
            "14. A template is a <font color=#0099ff>(RBI Grade B 2014)</font>",
            "(1) pattern of worksheet",
            "(2) heading",
            "(3) title",
            "(4) theme",
            "(5) None of the above",
            "15. E-mail client is the feature of",
            "(1) MS-Word ",
            "(2) MS-Excel",
            "(3) MS-PowerPoint ",
            "(4) MS-Access",
            "(5) MS-Outlook",
            "16. Which bar is usually located below title bar that provides categorised options?",
            "(1) Menu bar ",
            "(2) Status bar",
            "(3) Tool bar ",
            "(4) Scroll bar",
            "(5) None of these",
            "17. The process of making changes to an existing document is referred to as … it. <font color=#0099ff>(SBI Clerk 2014)</font>",
            "(1) editing ",
            "(2) changing",
            "(3) modifying ",
            "(4) creating",
            "(5) adjusting",
            "18. Most of the editing tools are available under which menu?",
            "(1) File ",
            "(2) Format",
            "(3) Edit ",
            "(4) All of these",
            "(5) None of these",
            "19. To move to the beginning of a line of text, press the … key.",
            "(1) Page up ",
            "(2) A",
            "(3) Home ",
            "(4) Enter",
            "(5) None of these",
            "20. In which menu, we will find the command document? <font color=#0099ff>(RBI Grade B 2013)</font>",
            "(1) File ",
            "(2) Insert",
            "(3) Tools ",
            "(4) Data",
            "(5) None of these"
    };
    String[] answersSet4 = {
            "(3)","(3)","(1)","(4)","(3)","(1)","(1)","(1)","(1)","(1)","(1)","(2)","(1)","(1)","(5)","(1)","(1)","(3)","(3)","(4)"

    };

    public String[] getQuestionsSet1() {
        return questionsSet1;
    }

    public String[] getAnswersSet1() {
        return answersSet1;
    }

    public String[] getQuestionsSet2() {
        return questionsSet2;
    }

    public String[] getAnswersSet2() {
        return answersSet2;
    }

    public String[] getQuestionsSet3() {
        return questionsSet3;
    }

    public String[] getAnswersSet3() {
        return answersSet3;
    }

    public String[] getQuestionsSet4() {
        return questionsSet4;
    }

    public String[] getAnswersSet4() {
        return answersSet4;
    }
}



